/* devpet.c generated by valac 0.40.4, the Vala compiler
 * generated from devpet.vala, do not modify */

/*
   Copyright (C) 2013 André Stösel <andre@stoesel.de>

   This library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include "midori/midori-extension.h"
#include <glib/gi18n-lib.h>
#include <execinfo.h>
#include "midori/midori-app.h"
#include "devpet.h"


#define DEV_PET_TYPE_TREE_CELLS (dev_pet_tree_cells_get_type ())

#define DEV_PET_TYPE_DATA_WINDOW (dev_pet_data_window_get_type ())
#define DEV_PET_DATA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindow))
#define DEV_PET_DATA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindowClass))
#define DEV_PET_IS_DATA_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DEV_PET_TYPE_DATA_WINDOW))
#define DEV_PET_IS_DATA_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DEV_PET_TYPE_DATA_WINDOW))
#define DEV_PET_DATA_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindowClass))

typedef struct _DevPetDataWindow DevPetDataWindow;
typedef struct _DevPetDataWindowClass DevPetDataWindowClass;
typedef struct _DevPetDataWindowPrivate DevPetDataWindowPrivate;
enum  {
	DEV_PET_DATA_WINDOW_0_PROPERTY,
	DEV_PET_DATA_WINDOW_MESSAGE_PROPERTY,
	DEV_PET_DATA_WINDOW_BACKTRACE_PROPERTY,
	DEV_PET_DATA_WINDOW_NUM_PROPERTIES
};
static GParamSpec* dev_pet_data_window_properties[DEV_PET_DATA_WINDOW_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define DEV_PET_TYPE_LOG_WINDOW (dev_pet_log_window_get_type ())
#define DEV_PET_LOG_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DEV_PET_TYPE_LOG_WINDOW, DevPetLogWindow))
#define DEV_PET_LOG_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DEV_PET_TYPE_LOG_WINDOW, DevPetLogWindowClass))
#define DEV_PET_IS_LOG_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DEV_PET_TYPE_LOG_WINDOW))
#define DEV_PET_IS_LOG_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DEV_PET_TYPE_LOG_WINDOW))
#define DEV_PET_LOG_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DEV_PET_TYPE_LOG_WINDOW, DevPetLogWindowClass))

typedef struct _DevPetLogWindow DevPetLogWindow;
typedef struct _DevPetLogWindowClass DevPetLogWindowClass;
typedef struct _DevPetLogWindowPrivate DevPetLogWindowPrivate;

#define DEV_PET_TYPE_MANAGER (dev_pet_manager_get_type ())
#define DEV_PET_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), DEV_PET_TYPE_MANAGER, DevPetManager))
#define DEV_PET_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), DEV_PET_TYPE_MANAGER, DevPetManagerClass))
#define DEV_PET_IS_MANAGER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), DEV_PET_TYPE_MANAGER))
#define DEV_PET_IS_MANAGER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), DEV_PET_TYPE_MANAGER))
#define DEV_PET_MANAGER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), DEV_PET_TYPE_MANAGER, DevPetManagerClass))

typedef struct _DevPetManager DevPetManager;
typedef struct _DevPetManagerClass DevPetManagerClass;
enum  {
	DEV_PET_LOG_WINDOW_0_PROPERTY,
	DEV_PET_LOG_WINDOW_NUM_PROPERTIES
};
static GParamSpec* dev_pet_log_window_properties[DEV_PET_LOG_WINDOW_NUM_PROPERTIES];
typedef struct _DevPetManagerPrivate DevPetManagerPrivate;
enum  {
	DEV_PET_MANAGER_0_PROPERTY,
	DEV_PET_MANAGER_NUM_PROPERTIES
};
static GParamSpec* dev_pet_manager_properties[DEV_PET_MANAGER_NUM_PROPERTIES];
typedef struct _Block1Data Block1Data;

typedef enum  {
	DEV_PET_TREE_CELLS_MESSAGE,
	DEV_PET_TREE_CELLS_BACKTRACE,
	DEV_PET_TREE_CELLS_STOCK,
	DEV_PET_TREE_CELLS_COUNT
} DevPetTreeCells;

struct _DevPetDataWindow {
	GtkWindow parent_instance;
	DevPetDataWindowPrivate * priv;
};

struct _DevPetDataWindowClass {
	GtkWindowClass parent_class;
};

struct _DevPetDataWindowPrivate {
	gchar* _message;
	gchar* _backtrace;
};

struct _DevPetLogWindow {
	GtkWindow parent_instance;
	DevPetLogWindowPrivate * priv;
};

struct _DevPetLogWindowClass {
	GtkWindowClass parent_class;
};

struct _DevPetLogWindowPrivate {
	DevPetManager* manager;
};

struct _DevPetManager {
	MidoriExtension parent_instance;
	DevPetManagerPrivate * priv;
	GtkListStore* list_store;
};

struct _DevPetManagerClass {
	MidoriExtensionClass parent_class;
};

struct _DevPetManagerPrivate {
	GtkStatusIcon* trayicon;
	DevPetLogWindow* log_window;
	GLogFunc default_log_func;
	gpointer default_log_func_target;
	GDestroyNotify default_log_func_target_destroy_notify;
	GLogLevelFlags icon_flag;
};

struct _Block1Data {
	int _ref_count_;
	DevPetManager* self;
	gint length;
};


extern GtkIconTheme* theme;
GtkIconTheme* theme = NULL;
static gpointer dev_pet_data_window_parent_class = NULL;
static gpointer dev_pet_log_window_parent_class = NULL;
static gpointer dev_pet_manager_parent_class = NULL;

GType dev_pet_tree_cells_get_type (void) G_GNUC_CONST;
GType dev_pet_data_window_get_type (void) G_GNUC_CONST;
#define DEV_PET_DATA_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindowPrivate))
static void dev_pet_data_window_create_content (DevPetDataWindow* self);
const gchar* dev_pet_data_window_get_message (DevPetDataWindow* self);
const gchar* dev_pet_data_window_get_backtrace (DevPetDataWindow* self);
DevPetDataWindow* dev_pet_data_window_new (const gchar* message,
                                           const gchar* backtrace);
DevPetDataWindow* dev_pet_data_window_construct (GType object_type,
                                                 const gchar* message,
                                                 const gchar* backtrace);
static void dev_pet_data_window_set_message (DevPetDataWindow* self,
                                      const gchar* value);
static void dev_pet_data_window_set_backtrace (DevPetDataWindow* self,
                                        const gchar* value);
static void dev_pet_data_window_finalize (GObject * obj);
static void _vala_dev_pet_data_window_get_property (GObject * object,
                                             guint property_id,
                                             GValue * value,
                                             GParamSpec * pspec);
static void _vala_dev_pet_data_window_set_property (GObject * object,
                                             guint property_id,
                                             const GValue * value,
                                             GParamSpec * pspec);
GType dev_pet_log_window_get_type (void) G_GNUC_CONST;
GType dev_pet_manager_get_type (void) G_GNUC_CONST;
#define DEV_PET_LOG_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DEV_PET_TYPE_LOG_WINDOW, DevPetLogWindowPrivate))
static void dev_pet_log_window_clear_list (DevPetLogWindow* self);
void dev_pet_manager_clear_list (DevPetManager* self);
static void dev_pet_log_window_row_activated (DevPetLogWindow* self,
                                       GtkTreePath* path,
                                       GtkTreeViewColumn* column);
static void dev_pet_log_window_create_content (DevPetLogWindow* self);
void dev_pet_manager_log_window_closed (DevPetManager* self);
static void _dev_pet_manager_log_window_closed_gtk_object_destroy (GtkObject* _sender,
                                                            gpointer self);
static void _dev_pet_log_window_clear_list_gtk_button_clicked (GtkButton* _sender,
                                                        gpointer self);
static void _dev_pet_log_window_row_activated_gtk_tree_view_row_activated (GtkTreeView* _sender,
                                                                    GtkTreePath* path,
                                                                    GtkTreeViewColumn* column,
                                                                    gpointer self);
DevPetLogWindow* dev_pet_log_window_new (DevPetManager* manager);
DevPetLogWindow* dev_pet_log_window_construct (GType object_type,
                                               DevPetManager* manager);
static void dev_pet_log_window_finalize (GObject * obj);
#define DEV_PET_MANAGER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), DEV_PET_TYPE_MANAGER, DevPetManagerPrivate))
static const gchar* dev_pet_manager_get_stock_from_log_level (DevPetManager* self,
                                                       GLogLevelFlags flags);
static void dev_pet_manager_ensure_trayicon (DevPetManager* self);
static void dev_pet_manager_show_error_log (DevPetManager* self);
static void _dev_pet_manager_show_error_log_gtk_status_icon_activate (GtkStatusIcon* _sender,
                                                               gpointer self);
static void dev_pet_manager_log_handler (DevPetManager* self,
                                  const gchar* domain,
                                  GLogLevelFlags flags,
                                  const gchar* message);
static void dev_pet_manager_activated (DevPetManager* self,
                                MidoriApp* app);
static void _dev_pet_manager_log_handler_glog_func (const gchar* log_domain,
                                             GLogLevelFlags log_levels,
                                             const gchar* message,
                                             gpointer self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static gboolean ___lambda4_ (Block1Data* _data1_,
                      GtkTreeModel* model,
                      GtkTreePath* path,
                      GtkTreeIter* iter);
static gboolean ____lambda4__gtk_tree_model_foreach_func (GtkTreeModel* model,
                                                   GtkTreePath* path,
                                                   GtkTreeIter* iter,
                                                   gpointer self);
static void dev_pet_manager_deactivated (DevPetManager* self);
DevPetManager* dev_pet_manager_new (void);
DevPetManager* dev_pet_manager_construct (GType object_type);
static void _dev_pet_manager_activated_midori_extension_activate (MidoriExtension* _sender,
                                                           MidoriApp* app,
                                                           gpointer self);
static void _dev_pet_manager_deactivated_midori_extension_deactivate (MidoriExtension* _sender,
                                                               gpointer self);
static void dev_pet_manager_finalize (GObject * obj);


GType
dev_pet_tree_cells_get_type (void)
{
	static volatile gsize dev_pet_tree_cells_type_id__volatile = 0;
	if (g_once_init_enter (&dev_pet_tree_cells_type_id__volatile)) {
		static const GEnumValue values[] = {{DEV_PET_TREE_CELLS_MESSAGE, "DEV_PET_TREE_CELLS_MESSAGE", "message"}, {DEV_PET_TREE_CELLS_BACKTRACE, "DEV_PET_TREE_CELLS_BACKTRACE", "backtrace"}, {DEV_PET_TREE_CELLS_STOCK, "DEV_PET_TREE_CELLS_STOCK", "stock"}, {DEV_PET_TREE_CELLS_COUNT, "DEV_PET_TREE_CELLS_COUNT", "count"}, {0, NULL, NULL}};
		GType dev_pet_tree_cells_type_id;
		dev_pet_tree_cells_type_id = g_enum_register_static ("DevPetTreeCells", values);
		g_once_init_leave (&dev_pet_tree_cells_type_id__volatile, dev_pet_tree_cells_type_id);
	}
	return dev_pet_tree_cells_type_id__volatile;
}


static void
dev_pet_data_window_create_content (DevPetDataWindow* self)
{
	const gchar* _tmp0_;
	GtkVBox* vbox = NULL;
	GtkVBox* _tmp1_;
	GtkTextBuffer* message_buffer = NULL;
	GtkTextBuffer* _tmp2_;
	const gchar* _tmp3_;
	GtkTextView* message_text_view = NULL;
	GtkTextView* _tmp4_;
	GtkTextBuffer* backtrace_buffer = NULL;
	GtkTextBuffer* _tmp5_;
	const gchar* _tmp6_;
	GtkTextView* backtrace_text_view = NULL;
	GtkTextView* _tmp7_;
	GtkScrolledWindow* message_scroll = NULL;
	GtkScrolledWindow* _tmp8_;
	GtkScrolledWindow* backtrace_scroll = NULL;
	GtkScrolledWindow* _tmp9_;
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->_message;
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_window_set_title ((GtkWindow*) self, _tmp0_);
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_window_set_default_size ((GtkWindow*) self, 500, 500);
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp1_ = (GtkVBox*) gtk_vbox_new (FALSE, 1);
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp1_);
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	vbox = _tmp1_;
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) vbox);
#line 33 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp2_ = gtk_text_buffer_new (NULL);
#line 33 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	message_buffer = _tmp2_;
#line 34 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp3_ = self->priv->_message;
#line 34 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_text_buffer_set_text (message_buffer, _tmp3_, -1);
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp4_ = (GtkTextView*) gtk_text_view_new_with_buffer (message_buffer);
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp4_);
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	message_text_view = _tmp4_;
#line 37 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_text_view_set_editable (message_text_view, FALSE);
#line 39 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp5_ = gtk_text_buffer_new (NULL);
#line 39 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	backtrace_buffer = _tmp5_;
#line 40 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp6_ = self->priv->_backtrace;
#line 40 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_text_buffer_set_text (backtrace_buffer, _tmp6_, -1);
#line 42 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp7_ = (GtkTextView*) gtk_text_view_new_with_buffer (backtrace_buffer);
#line 42 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp7_);
#line 42 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	backtrace_text_view = _tmp7_;
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_text_view_set_editable (backtrace_text_view, FALSE);
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp8_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp8_);
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	message_scroll = _tmp8_;
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_scrolled_window_set_policy (message_scroll, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
#line 47 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_container_add ((GtkContainer*) message_scroll, (GtkWidget*) message_text_view);
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp9_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp9_);
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	backtrace_scroll = _tmp9_;
#line 50 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_scrolled_window_set_policy (backtrace_scroll, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
#line 51 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_container_add ((GtkContainer*) backtrace_scroll, (GtkWidget*) backtrace_text_view);
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) message_scroll, FALSE, FALSE, (guint) 0);
#line 54 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_box_pack_end ((GtkBox*) vbox, (GtkWidget*) backtrace_scroll, TRUE, TRUE, (guint) 0);
#line 56 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (backtrace_scroll);
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (message_scroll);
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (backtrace_text_view);
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (backtrace_buffer);
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (message_text_view);
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (message_buffer);
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (vbox);
#line 356 "devpet.c"
}


DevPetDataWindow*
dev_pet_data_window_construct (GType object_type,
                               const gchar* message,
                               const gchar* backtrace)
{
	DevPetDataWindow * self = NULL;
#line 59 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_val_if_fail (message != NULL, NULL);
#line 59 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_val_if_fail (backtrace != NULL, NULL);
#line 60 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self = (DevPetDataWindow*) g_object_new (object_type, "type", GTK_WINDOW_TOPLEVEL, "window-position", GTK_WIN_POS_CENTER, "message", message, "backtrace", backtrace, NULL);
#line 65 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_data_window_create_content (self);
#line 59 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return self;
#line 376 "devpet.c"
}


DevPetDataWindow*
dev_pet_data_window_new (const gchar* message,
                         const gchar* backtrace)
{
#line 59 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return dev_pet_data_window_construct (DEV_PET_TYPE_DATA_WINDOW, message, backtrace);
#line 386 "devpet.c"
}


const gchar*
dev_pet_data_window_get_message (DevPetDataWindow* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->_message;
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	result = _tmp0_;
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return result;
#line 403 "devpet.c"
}


static void
dev_pet_data_window_set_message (DevPetDataWindow* self,
                                 const gchar* value)
{
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (g_strcmp0 (value, dev_pet_data_window_get_message (self)) != 0) {
#line 415 "devpet.c"
		gchar* _tmp0_;
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp0_ = g_strdup (value);
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_g_free0 (self->priv->_message);
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		self->priv->_message = _tmp0_;
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		g_object_notify_by_pspec ((GObject *) self, dev_pet_data_window_properties[DEV_PET_DATA_WINDOW_MESSAGE_PROPERTY]);
#line 425 "devpet.c"
	}
}


const gchar*
dev_pet_data_window_get_backtrace (DevPetDataWindow* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->_backtrace;
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	result = _tmp0_;
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return result;
#line 443 "devpet.c"
}


static void
dev_pet_data_window_set_backtrace (DevPetDataWindow* self,
                                   const gchar* value)
{
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (g_strcmp0 (value, dev_pet_data_window_get_backtrace (self)) != 0) {
#line 455 "devpet.c"
		gchar* _tmp0_;
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp0_ = g_strdup (value);
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_g_free0 (self->priv->_backtrace);
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		self->priv->_backtrace = _tmp0_;
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		g_object_notify_by_pspec ((GObject *) self, dev_pet_data_window_properties[DEV_PET_DATA_WINDOW_BACKTRACE_PROPERTY]);
#line 465 "devpet.c"
	}
}


static void
dev_pet_data_window_class_init (DevPetDataWindowClass * klass)
{
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_data_window_parent_class = g_type_class_peek_parent (klass);
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_type_class_add_private (klass, sizeof (DevPetDataWindowPrivate));
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_dev_pet_data_window_get_property;
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_dev_pet_data_window_set_property;
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (klass)->finalize = dev_pet_data_window_finalize;
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), DEV_PET_DATA_WINDOW_MESSAGE_PROPERTY, dev_pet_data_window_properties[DEV_PET_DATA_WINDOW_MESSAGE_PROPERTY] = g_param_spec_string ("message", "message", "message", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), DEV_PET_DATA_WINDOW_BACKTRACE_PROPERTY, dev_pet_data_window_properties[DEV_PET_DATA_WINDOW_BACKTRACE_PROPERTY] = g_param_spec_string ("backtrace", "backtrace", "backtrace", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 487 "devpet.c"
}


static void
dev_pet_data_window_instance_init (DevPetDataWindow * self)
{
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv = DEV_PET_DATA_WINDOW_GET_PRIVATE (self);
#line 496 "devpet.c"
}


static void
dev_pet_data_window_finalize (GObject * obj)
{
	DevPetDataWindow * self;
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindow);
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_free0 (self->priv->_message);
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_free0 (self->priv->_backtrace);
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (dev_pet_data_window_parent_class)->finalize (obj);
#line 512 "devpet.c"
}


GType
dev_pet_data_window_get_type (void)
{
	static volatile gsize dev_pet_data_window_type_id__volatile = 0;
	if (g_once_init_enter (&dev_pet_data_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DevPetDataWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dev_pet_data_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DevPetDataWindow), 0, (GInstanceInitFunc) dev_pet_data_window_instance_init, NULL };
		GType dev_pet_data_window_type_id;
		dev_pet_data_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "DevPetDataWindow", &g_define_type_info, 0);
		g_once_init_leave (&dev_pet_data_window_type_id__volatile, dev_pet_data_window_type_id);
	}
	return dev_pet_data_window_type_id__volatile;
}


static void
_vala_dev_pet_data_window_get_property (GObject * object,
                                        guint property_id,
                                        GValue * value,
                                        GParamSpec * pspec)
{
	DevPetDataWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindow);
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	switch (property_id) {
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		case DEV_PET_DATA_WINDOW_MESSAGE_PROPERTY:
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		g_value_set_string (value, dev_pet_data_window_get_message (self));
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		break;
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		case DEV_PET_DATA_WINDOW_BACKTRACE_PROPERTY:
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		g_value_set_string (value, dev_pet_data_window_get_backtrace (self));
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		break;
#line 552 "devpet.c"
		default:
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		break;
#line 558 "devpet.c"
	}
}


static void
_vala_dev_pet_data_window_set_property (GObject * object,
                                        guint property_id,
                                        const GValue * value,
                                        GParamSpec * pspec)
{
	DevPetDataWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, DEV_PET_TYPE_DATA_WINDOW, DevPetDataWindow);
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	switch (property_id) {
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		case DEV_PET_DATA_WINDOW_MESSAGE_PROPERTY:
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		dev_pet_data_window_set_message (self, g_value_get_string (value));
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		break;
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		case DEV_PET_DATA_WINDOW_BACKTRACE_PROPERTY:
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		dev_pet_data_window_set_backtrace (self, g_value_get_string (value));
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		break;
#line 585 "devpet.c"
		default:
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		break;
#line 591 "devpet.c"
	}
}


static void
dev_pet_log_window_clear_list (DevPetLogWindow* self)
{
	DevPetManager* _tmp0_;
#line 72 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 73 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->manager;
#line 73 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_manager_clear_list (_tmp0_);
#line 74 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_object_destroy ((GtkObject*) self);
#line 608 "devpet.c"
}


static void
dev_pet_log_window_row_activated (DevPetLogWindow* self,
                                  GtkTreePath* path,
                                  GtkTreeViewColumn* column)
{
	GtkTreeIter iter = {0};
	DevPetManager* _tmp0_;
	GtkListStore* _tmp1_;
	GtkTreeIter _tmp2_ = {0};
	gboolean _tmp3_;
#line 78 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 78 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (path != NULL);
#line 78 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (column != NULL);
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->manager;
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp1_ = _tmp0_->list_store;
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp3_ = gtk_tree_model_get_iter ((GtkTreeModel*) _tmp1_, &_tmp2_, path);
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	iter = _tmp2_;
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (_tmp3_) {
#line 638 "devpet.c"
		gchar* message = NULL;
		gchar* backtrace = NULL;
		DevPetManager* _tmp4_;
		GtkListStore* _tmp5_;
		GtkTreeIter _tmp6_;
		DevPetDataWindow* data_window = NULL;
		const gchar* _tmp7_;
		const gchar* _tmp8_;
		DevPetDataWindow* _tmp9_;
		DevPetDataWindow* _tmp10_;
#line 83 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp4_ = self->priv->manager;
#line 83 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp5_ = _tmp4_->list_store;
#line 83 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp6_ = iter;
#line 83 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		gtk_tree_model_get ((GtkTreeModel*) _tmp5_, &_tmp6_, DEV_PET_TREE_CELLS_MESSAGE, &message, DEV_PET_TREE_CELLS_BACKTRACE, &backtrace, -1, -1);
#line 87 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp7_ = message;
#line 87 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp8_ = backtrace;
#line 87 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp9_ = dev_pet_data_window_new (_tmp7_, _tmp8_);
#line 87 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		g_object_ref_sink (_tmp9_);
#line 87 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		data_window = _tmp9_;
#line 88 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp10_ = data_window;
#line 88 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		gtk_widget_show ((GtkWidget*) _tmp10_);
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_g_object_unref0 (data_window);
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_g_free0 (backtrace);
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_g_free0 (message);
#line 677 "devpet.c"
	}
}


static void
_dev_pet_manager_log_window_closed_gtk_object_destroy (GtkObject* _sender,
                                                       gpointer self)
{
#line 96 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_manager_log_window_closed ((DevPetManager*) self);
#line 688 "devpet.c"
}


static void
_dev_pet_log_window_clear_list_gtk_button_clicked (GtkButton* _sender,
                                                   gpointer self)
{
#line 112 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_log_window_clear_list ((DevPetLogWindow*) self);
#line 698 "devpet.c"
}


static void
_dev_pet_log_window_row_activated_gtk_tree_view_row_activated (GtkTreeView* _sender,
                                                               GtkTreePath* path,
                                                               GtkTreeViewColumn* column,
                                                               gpointer self)
{
#line 129 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_log_window_row_activated ((DevPetLogWindow*) self, path, column);
#line 710 "devpet.c"
}


static void
dev_pet_log_window_create_content (DevPetLogWindow* self)
{
	DevPetManager* _tmp0_;
	GtkVBox* vbox = NULL;
	GtkVBox* _tmp1_;
	GtkLabel* label = NULL;
	GtkLabel* _tmp2_;
	GtkScrolledWindow* scroll_windows = NULL;
	GtkScrolledWindow* _tmp3_;
	GtkButton* clear = NULL;
	GtkButton* _tmp4_;
	GtkTreeView* treeview = NULL;
	DevPetManager* _tmp5_;
	GtkListStore* _tmp6_;
	GtkTreeView* _tmp7_;
	GtkCellRendererPixbuf* _tmp8_;
	GtkCellRendererPixbuf* _tmp9_;
	GtkCellRendererText* _tmp10_;
	GtkCellRendererText* _tmp11_;
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 94 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_window_set_title ((GtkWindow*) self, "Midori - DevPet");
#line 95 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_window_set_default_size ((GtkWindow*) self, 500, 250);
#line 96 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->manager;
#line 96 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_signal_connect_object ((GtkObject*) self, "destroy", (GCallback) _dev_pet_manager_log_window_closed_gtk_object_destroy, _tmp0_, 0);
#line 98 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp1_ = (GtkVBox*) gtk_vbox_new (FALSE, 1);
#line 98 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp1_);
#line 98 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	vbox = _tmp1_;
#line 99 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) vbox);
#line 102 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp2_ = (GtkLabel*) gtk_label_new (_ ("Double click for more information"));
#line 102 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp2_);
#line 102 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	label = _tmp2_;
#line 103 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) label, FALSE, FALSE, (guint) 0);
#line 106 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp3_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
#line 106 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp3_);
#line 106 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	scroll_windows = _tmp3_;
#line 107 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_scrolled_window_set_policy (scroll_windows, GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
#line 108 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_scrolled_window_set_shadow_type (scroll_windows, GTK_SHADOW_ETCHED_IN);
#line 111 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp4_ = (GtkButton*) gtk_button_new_from_stock ("gtk-clear");
#line 111 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp4_);
#line 111 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	clear = _tmp4_;
#line 112 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_signal_connect_object (clear, "clicked", (GCallback) _dev_pet_log_window_clear_list_gtk_button_clicked, self, 0);
#line 114 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) scroll_windows, TRUE, TRUE, (guint) 0);
#line 115 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_box_pack_start ((GtkBox*) vbox, (GtkWidget*) clear, FALSE, FALSE, (guint) 0);
#line 118 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp5_ = self->priv->manager;
#line 118 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp6_ = _tmp5_->list_store;
#line 118 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp7_ = (GtkTreeView*) gtk_tree_view_new_with_model ((GtkTreeModel*) _tmp6_);
#line 118 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp7_);
#line 118 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	treeview = _tmp7_;
#line 119 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_container_add ((GtkContainer*) scroll_windows, (GtkWidget*) treeview);
#line 121 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp8_ = (GtkCellRendererPixbuf*) gtk_cell_renderer_pixbuf_new ();
#line 121 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp8_);
#line 121 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp9_ = _tmp8_;
#line 121 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_tree_view_insert_column_with_attributes (treeview, -1, "Type", (GtkCellRenderer*) _tmp9_, "stock-id", DEV_PET_TREE_CELLS_STOCK, NULL);
#line 121 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (_tmp9_);
#line 124 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp10_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
#line 124 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_object_ref_sink (_tmp10_);
#line 124 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp11_ = _tmp10_;
#line 124 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_tree_view_insert_column_with_attributes (treeview, -1, "Message", (GtkCellRenderer*) _tmp11_, "text", DEV_PET_TREE_CELLS_MESSAGE, NULL);
#line 124 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (_tmp11_);
#line 129 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_signal_connect_object (treeview, "row-activated", (GCallback) _dev_pet_log_window_row_activated_gtk_tree_view_row_activated, self, 0);
#line 132 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (treeview);
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (clear);
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (scroll_windows);
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (label);
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (vbox);
#line 828 "devpet.c"
}


static gpointer
_g_object_ref0 (gpointer self)
{
#line 139 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return self ? g_object_ref (self) : NULL;
#line 837 "devpet.c"
}


DevPetLogWindow*
dev_pet_log_window_construct (GType object_type,
                              DevPetManager* manager)
{
	DevPetLogWindow * self = NULL;
	DevPetManager* _tmp0_;
#line 135 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_val_if_fail (manager != NULL, NULL);
#line 136 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self = (DevPetLogWindow*) g_object_new (object_type, "type", GTK_WINDOW_TOPLEVEL, "window-position", GTK_WIN_POS_CENTER, NULL);
#line 139 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = _g_object_ref0 (manager);
#line 139 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->manager);
#line 139 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->manager = _tmp0_;
#line 140 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_log_window_create_content (self);
#line 135 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return self;
#line 861 "devpet.c"
}


DevPetLogWindow*
dev_pet_log_window_new (DevPetManager* manager)
{
#line 135 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return dev_pet_log_window_construct (DEV_PET_TYPE_LOG_WINDOW, manager);
#line 870 "devpet.c"
}


static void
dev_pet_log_window_class_init (DevPetLogWindowClass * klass)
{
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_log_window_parent_class = g_type_class_peek_parent (klass);
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_type_class_add_private (klass, sizeof (DevPetLogWindowPrivate));
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (klass)->finalize = dev_pet_log_window_finalize;
#line 883 "devpet.c"
}


static void
dev_pet_log_window_instance_init (DevPetLogWindow * self)
{
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv = DEV_PET_LOG_WINDOW_GET_PRIVATE (self);
#line 892 "devpet.c"
}


static void
dev_pet_log_window_finalize (GObject * obj)
{
	DevPetLogWindow * self;
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DEV_PET_TYPE_LOG_WINDOW, DevPetLogWindow);
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->manager);
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (dev_pet_log_window_parent_class)->finalize (obj);
#line 906 "devpet.c"
}


GType
dev_pet_log_window_get_type (void)
{
	static volatile gsize dev_pet_log_window_type_id__volatile = 0;
	if (g_once_init_enter (&dev_pet_log_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DevPetLogWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dev_pet_log_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DevPetLogWindow), 0, (GInstanceInitFunc) dev_pet_log_window_instance_init, NULL };
		GType dev_pet_log_window_type_id;
		dev_pet_log_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "DevPetLogWindow", &g_define_type_info, 0);
		g_once_init_leave (&dev_pet_log_window_type_id__volatile, dev_pet_log_window_type_id);
	}
	return dev_pet_log_window_type_id__volatile;
}


void
dev_pet_manager_clear_list (DevPetManager* self)
{
	GtkStatusIcon* _tmp0_;
	GtkListStore* _tmp2_;
#line 151 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 152 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->icon_flag = G_LOG_LEVEL_DEBUG;
#line 153 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->trayicon;
#line 153 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (_tmp0_ != NULL) {
#line 937 "devpet.c"
		GtkStatusIcon* _tmp1_;
#line 154 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp1_ = self->priv->trayicon;
#line 154 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		gtk_status_icon_set_visible (_tmp1_, FALSE);
#line 943 "devpet.c"
	}
#line 155 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp2_ = self->list_store;
#line 155 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_list_store_clear (_tmp2_);
#line 949 "devpet.c"
}


void
dev_pet_manager_log_window_closed (DevPetManager* self)
{
#line 158 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 159 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->log_window);
#line 159 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->log_window = NULL;
#line 962 "devpet.c"
}


static const gchar*
dev_pet_manager_get_stock_from_log_level (DevPetManager* self,
                                          GLogLevelFlags flags)
{
	const gchar* result = NULL;
	gboolean _tmp0_ = FALSE;
#line 162 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 163 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if ((flags & G_LOG_LEVEL_CRITICAL) == flags) {
#line 163 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp0_ = TRUE;
#line 978 "devpet.c"
	} else {
#line 163 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp0_ = (flags & G_LOG_LEVEL_ERROR) == flags;
#line 982 "devpet.c"
	}
#line 163 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (_tmp0_) {
#line 164 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		result = GTK_STOCK_DIALOG_ERROR;
#line 164 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		return result;
#line 990 "devpet.c"
	} else {
#line 165 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		if ((flags & G_LOG_LEVEL_WARNING) == flags) {
#line 166 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
			result = GTK_STOCK_DIALOG_WARNING;
#line 166 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
			return result;
#line 998 "devpet.c"
		}
	}
#line 168 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	result = GTK_STOCK_DIALOG_INFO;
#line 168 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return result;
#line 1005 "devpet.c"
}


static void
_dev_pet_manager_show_error_log_gtk_status_icon_activate (GtkStatusIcon* _sender,
                                                          gpointer self)
{
#line 177 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_manager_show_error_log ((DevPetManager*) self);
#line 1015 "devpet.c"
}


static void
dev_pet_manager_ensure_trayicon (DevPetManager* self)
{
	GtkStatusIcon* _tmp0_;
	GtkStatusIcon* _tmp1_;
	GtkStatusIcon* _tmp2_;
	GtkStatusIcon* _tmp3_;
#line 171 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 172 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->trayicon;
#line 172 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (_tmp0_ != NULL) {
#line 173 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		return;
#line 1034 "devpet.c"
	}
#line 175 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp1_ = gtk_status_icon_new ();
#line 175 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->trayicon);
#line 175 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->trayicon = _tmp1_;
#line 176 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp2_ = self->priv->trayicon;
#line 176 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_status_icon_set_tooltip_text (_tmp2_, "Midori - DevPet");
#line 177 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp3_ = self->priv->trayicon;
#line 177 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_signal_connect_object (_tmp3_, "activate", (GCallback) _dev_pet_manager_show_error_log_gtk_status_icon_activate, self, 0);
#line 1050 "devpet.c"
}


static void
dev_pet_manager_log_handler (DevPetManager* self,
                             const gchar* domain,
                             GLogLevelFlags flags,
                             const gchar* message)
{
	GtkTreeIter iter = {0};
	const gchar* stock = NULL;
	const gchar* _tmp0_;
	GLogLevelFlags _tmp1_;
	gchar* bt = NULL;
	gchar* _tmp4_;
	void* buffer[100] = {0};
	gint num = 0;
	gchar** symbols = NULL;
	gint _tmp5_;
	gchar** _tmp6_;
	gint symbols_length1;
	gint _symbols_size_;
	gchar** _tmp7_;
	gint _tmp7__length1;
	GtkListStore* _tmp19_;
	GtkTreeIter _tmp20_ = {0};
	GtkListStore* _tmp21_;
	GtkTreeIter _tmp22_;
	const gchar* _tmp23_;
	const gchar* _tmp24_;
	GtkStatusIcon* _tmp25_;
#line 180 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 180 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (message != NULL);
#line 182 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = dev_pet_manager_get_stock_from_log_level (self, flags);
#line 182 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	stock = _tmp0_;
#line 184 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_manager_ensure_trayicon (self);
#line 186 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp1_ = self->priv->icon_flag;
#line 186 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (flags < _tmp1_) {
#line 1096 "devpet.c"
		GtkStatusIcon* _tmp2_;
		const gchar* _tmp3_;
#line 187 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		self->priv->icon_flag = flags;
#line 188 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp2_ = self->priv->trayicon;
#line 188 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp3_ = stock;
#line 188 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		gtk_status_icon_set_from_stock (_tmp2_, _tmp3_);
#line 1107 "devpet.c"
	}
#line 192 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp4_ = g_strdup ("");
#line 192 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	bt = _tmp4_;
#line 194 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	num = backtrace (buffer, 100);
#line 196 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp5_ = num;
#line 196 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp6_ = backtrace_symbols (buffer, _tmp5_);
#line 196 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	symbols = _tmp6_;
#line 196 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	symbols_length1 = -1;
#line 196 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_symbols_size_ = symbols_length1;
#line 197 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp7_ = symbols;
#line 197 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp7__length1 = symbols_length1;
#line 197 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (_tmp7_ != NULL) {
#line 1131 "devpet.c"
		{
			gint i = 0;
#line 199 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
			i = 3;
#line 1136 "devpet.c"
			{
				gboolean _tmp8_ = FALSE;
#line 199 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
				_tmp8_ = TRUE;
#line 199 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
				while (TRUE) {
#line 1143 "devpet.c"
					gint _tmp10_;
					gint _tmp11_;
					const gchar* _tmp12_;
					gchar** _tmp13_;
					gint _tmp13__length1;
					gint _tmp14_;
					const gchar* _tmp15_;
					gchar* _tmp16_;
					gchar* _tmp17_;
					gchar* _tmp18_;
#line 199 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					if (!_tmp8_) {
#line 1156 "devpet.c"
						gint _tmp9_;
#line 199 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
						_tmp9_ = i;
#line 199 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
						i = _tmp9_ + 1;
#line 1162 "devpet.c"
					}
#line 199 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_tmp8_ = FALSE;
#line 199 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_tmp10_ = i;
#line 199 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_tmp11_ = num;
#line 199 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					if (!(_tmp10_ < _tmp11_)) {
#line 199 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
						break;
#line 1174 "devpet.c"
					}
#line 200 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_tmp12_ = bt;
#line 200 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_tmp13_ = symbols;
#line 200 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_tmp13__length1 = symbols_length1;
#line 200 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_tmp14_ = i;
#line 200 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_tmp15_ = _tmp13_[_tmp14_];
#line 200 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_tmp16_ = g_strdup_printf ("\r\n%s", _tmp15_);
#line 200 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_tmp17_ = _tmp16_;
#line 200 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_tmp18_ = g_strconcat (_tmp12_, _tmp17_, NULL);
#line 200 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_g_free0 (bt);
#line 200 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					bt = _tmp18_;
#line 200 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
					_g_free0 (_tmp17_);
#line 1198 "devpet.c"
				}
			}
		}
	}
#line 205 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp19_ = self->list_store;
#line 205 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_list_store_append (_tmp19_, &_tmp20_);
#line 205 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	iter = _tmp20_;
#line 206 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp21_ = self->list_store;
#line 206 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp22_ = iter;
#line 206 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp23_ = bt;
#line 206 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp24_ = stock;
#line 206 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_list_store_set (_tmp21_, &_tmp22_, DEV_PET_TREE_CELLS_MESSAGE, message, DEV_PET_TREE_CELLS_BACKTRACE, _tmp23_, DEV_PET_TREE_CELLS_STOCK, _tmp24_, -1);
#line 213 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp25_ = self->priv->trayicon;
#line 213 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	gtk_status_icon_set_visible (_tmp25_, TRUE);
#line 180 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_free0 (bt);
#line 1225 "devpet.c"
}


static void
dev_pet_manager_show_error_log (DevPetManager* self)
{
	DevPetLogWindow* _tmp0_;
#line 216 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 217 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->log_window;
#line 217 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (_tmp0_ == NULL) {
#line 1239 "devpet.c"
		DevPetLogWindow* _tmp1_;
		DevPetLogWindow* _tmp2_;
#line 218 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp1_ = dev_pet_log_window_new (self);
#line 218 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		g_object_ref_sink (_tmp1_);
#line 218 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_g_object_unref0 (self->priv->log_window);
#line 218 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		self->priv->log_window = _tmp1_;
#line 219 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp2_ = self->priv->log_window;
#line 219 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		gtk_widget_show ((GtkWidget*) _tmp2_);
#line 1254 "devpet.c"
	} else {
		DevPetLogWindow* _tmp3_;
		gboolean _tmp4_;
		gboolean _tmp5_;
#line 221 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp3_ = self->priv->log_window;
#line 221 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		g_object_get ((GtkWindow*) _tmp3_, "is-active", &_tmp4_, NULL);
#line 221 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp5_ = _tmp4_;
#line 221 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		if (_tmp5_) {
#line 1267 "devpet.c"
			DevPetLogWindow* _tmp6_;
#line 222 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
			_tmp6_ = self->priv->log_window;
#line 222 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
			gtk_widget_hide ((GtkWidget*) _tmp6_);
#line 1273 "devpet.c"
		} else {
			DevPetLogWindow* _tmp7_;
#line 224 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
			_tmp7_ = self->priv->log_window;
#line 224 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
			gtk_window_present ((GtkWindow*) _tmp7_);
#line 1280 "devpet.c"
		}
	}
}


static void
_dev_pet_manager_log_handler_glog_func (const gchar* log_domain,
                                        GLogLevelFlags log_levels,
                                        const gchar* message,
                                        gpointer self)
{
#line 231 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_manager_log_handler ((DevPetManager*) self, log_domain, log_levels, message);
#line 1294 "devpet.c"
}


static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return _data1_;
#line 1305 "devpet.c"
}


static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 1316 "devpet.c"
		DevPetManager* self;
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		self = _data1_->self;
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_g_object_unref0 (self);
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		g_slice_free (Block1Data, _data1_);
#line 1324 "devpet.c"
	}
}


static gboolean
___lambda4_ (Block1Data* _data1_,
             GtkTreeModel* model,
             GtkTreePath* path,
             GtkTreeIter* iter)
{
	DevPetManager* self;
	gboolean result = FALSE;
	gint _tmp0_;
#line 234 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self = _data1_->self;
#line 234 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_val_if_fail (model != NULL, FALSE);
#line 234 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_val_if_fail (path != NULL, FALSE);
#line 234 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_val_if_fail (iter != NULL, FALSE);
#line 235 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = _data1_->length;
#line 235 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_data1_->length = _tmp0_ + 1;
#line 236 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	result = FALSE;
#line 236 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return result;
#line 1354 "devpet.c"
}


static gboolean
____lambda4__gtk_tree_model_foreach_func (GtkTreeModel* model,
                                          GtkTreePath* path,
                                          GtkTreeIter* iter,
                                          gpointer self)
{
	gboolean result;
	result = ___lambda4_ (self, model, path, iter);
#line 234 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return result;
#line 1368 "devpet.c"
}


static void
dev_pet_manager_activated (DevPetManager* self,
                           MidoriApp* app)
{
	GLogFunc _tmp0_;
	void* _tmp0__target;
	GtkStatusIcon* _tmp1_;
#line 229 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 229 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (app != NULL);
#line 230 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = g_log_default_handler;
#line 230 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0__target = NULL;
#line 230 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	(self->priv->default_log_func_target_destroy_notify == NULL) ? NULL : (self->priv->default_log_func_target_destroy_notify (self->priv->default_log_func_target), NULL);
#line 230 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->default_log_func = NULL;
#line 230 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->default_log_func_target = NULL;
#line 230 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->default_log_func_target_destroy_notify = NULL;
#line 230 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->default_log_func = _tmp0_;
#line 230 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->default_log_func_target = _tmp0__target;
#line 230 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->default_log_func_target_destroy_notify = NULL;
#line 231 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_log_set_default_handler (_dev_pet_manager_log_handler_glog_func, self);
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp1_ = self->priv->trayicon;
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (_tmp1_ != NULL) {
#line 1407 "devpet.c"
		Block1Data* _data1_;
		GtkListStore* _tmp2_;
		gint _tmp3_;
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_data1_ = g_slice_new0 (Block1Data);
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_data1_->_ref_count_ = 1;
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_data1_->self = g_object_ref (self);
#line 233 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_data1_->length = 0;
#line 234 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp2_ = self->list_store;
#line 234 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		gtk_tree_model_foreach ((GtkTreeModel*) _tmp2_, ____lambda4__gtk_tree_model_foreach_func, _data1_);
#line 239 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp3_ = _data1_->length;
#line 239 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		if (_tmp3_ > 0) {
#line 1427 "devpet.c"
			GtkStatusIcon* _tmp4_;
#line 240 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
			_tmp4_ = self->priv->trayicon;
#line 240 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
			gtk_status_icon_set_visible (_tmp4_, TRUE);
#line 1433 "devpet.c"
		}
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		block1_data_unref (_data1_);
#line 232 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_data1_ = NULL;
#line 1439 "devpet.c"
	}
}


static void
dev_pet_manager_deactivated (DevPetManager* self)
{
	GtkStatusIcon* _tmp0_;
	GLogFunc _tmp2_;
	void* _tmp2__target;
#line 245 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_return_if_fail (self != NULL);
#line 246 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = self->priv->trayicon;
#line 246 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	if (_tmp0_ != NULL) {
#line 1456 "devpet.c"
		GtkStatusIcon* _tmp1_;
#line 247 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		_tmp1_ = self->priv->trayicon;
#line 247 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
		gtk_status_icon_set_visible (_tmp1_, FALSE);
#line 1462 "devpet.c"
	}
#line 249 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp2_ = self->priv->default_log_func;
#line 249 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp2__target = self->priv->default_log_func_target;
#line 249 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_log_set_default_handler (_tmp2_, _tmp2__target);
#line 1470 "devpet.c"
}


static void
_dev_pet_manager_activated_midori_extension_activate (MidoriExtension* _sender,
                                                      MidoriApp* app,
                                                      gpointer self)
{
#line 260 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_manager_activated ((DevPetManager*) self, app);
#line 1481 "devpet.c"
}


static void
_dev_pet_manager_deactivated_midori_extension_deactivate (MidoriExtension* _sender,
                                                          gpointer self)
{
#line 261 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_manager_deactivated ((DevPetManager*) self);
#line 1491 "devpet.c"
}


DevPetManager*
dev_pet_manager_construct (GType object_type)
{
	DevPetManager * self = NULL;
	GtkListStore* _tmp0_;
#line 253 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self = (DevPetManager*) g_object_new (object_type, "name", _ ("DevPet"), "description", _ ("This extension shows glib error messages in systray."), "version", "0.1", "authors", "André Stösel <andre@stoesel.de>", NULL);
#line 258 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = gtk_list_store_new ((gint) DEV_PET_TREE_CELLS_COUNT, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);
#line 258 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (self->list_store);
#line 258 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->list_store = _tmp0_;
#line 260 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_signal_connect_object ((MidoriExtension*) self, "activate", (GCallback) _dev_pet_manager_activated_midori_extension_activate, self, 0);
#line 261 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_signal_connect_object ((MidoriExtension*) self, "deactivate", (GCallback) _dev_pet_manager_deactivated_midori_extension_deactivate, self, 0);
#line 252 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return self;
#line 1514 "devpet.c"
}


DevPetManager*
dev_pet_manager_new (void)
{
#line 252 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return dev_pet_manager_construct (DEV_PET_TYPE_MANAGER);
#line 1523 "devpet.c"
}


static void
dev_pet_manager_class_init (DevPetManagerClass * klass)
{
#line 144 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	dev_pet_manager_parent_class = g_type_class_peek_parent (klass);
#line 144 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	g_type_class_add_private (klass, sizeof (DevPetManagerPrivate));
#line 144 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (klass)->finalize = dev_pet_manager_finalize;
#line 1536 "devpet.c"
}


static void
dev_pet_manager_instance_init (DevPetManager * self)
{
#line 144 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv = DEV_PET_MANAGER_GET_PRIVATE (self);
#line 146 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->trayicon = NULL;
#line 149 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->icon_flag = G_LOG_LEVEL_DEBUG;
#line 1549 "devpet.c"
}


static void
dev_pet_manager_finalize (GObject * obj)
{
	DevPetManager * self;
#line 144 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, DEV_PET_TYPE_MANAGER, DevPetManager);
#line 145 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (self->list_store);
#line 146 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->trayicon);
#line 147 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (self->priv->log_window);
#line 148 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	(self->priv->default_log_func_target_destroy_notify == NULL) ? NULL : (self->priv->default_log_func_target_destroy_notify (self->priv->default_log_func_target), NULL);
#line 148 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->default_log_func = NULL;
#line 148 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->default_log_func_target = NULL;
#line 148 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	self->priv->default_log_func_target_destroy_notify = NULL;
#line 144 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	G_OBJECT_CLASS (dev_pet_manager_parent_class)->finalize (obj);
#line 1575 "devpet.c"
}


GType
dev_pet_manager_get_type (void)
{
	static volatile gsize dev_pet_manager_type_id__volatile = 0;
	if (g_once_init_enter (&dev_pet_manager_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (DevPetManagerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) dev_pet_manager_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (DevPetManager), 0, (GInstanceInitFunc) dev_pet_manager_instance_init, NULL };
		GType dev_pet_manager_type_id;
		dev_pet_manager_type_id = g_type_register_static (MIDORI_TYPE_EXTENSION, "DevPetManager", &g_define_type_info, 0);
		g_once_init_leave (&dev_pet_manager_type_id__volatile, dev_pet_manager_type_id);
	}
	return dev_pet_manager_type_id__volatile;
}


MidoriExtension*
extension_init (void)
{
	MidoriExtension* result = NULL;
	GtkIconTheme* _tmp0_;
	GtkIconTheme* _tmp1_;
	DevPetManager* _tmp2_;
#line 267 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp0_ = gtk_icon_theme_get_default ();
#line 267 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 267 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_g_object_unref0 (theme);
#line 267 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	theme = _tmp1_;
#line 268 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	_tmp2_ = dev_pet_manager_new ();
#line 268 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	result = (MidoriExtension*) _tmp2_;
#line 268 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/devpet.vala"
	return result;
#line 1614 "devpet.c"
}



