/* open-with.h generated by valac 0.40.4, the Vala compiler, do not modify */


#ifndef __OPEN_WITH_H__
#define __OPEN_WITH_H__

#include <glib.h>
#include "midori/midori-extension.h"

G_BEGIN_DECLS



MidoriExtension* extension_init (void);


G_END_DECLS

#endif
