/* actions.c generated by valac 0.40.4, the Vala compiler
 * generated from actions.vala, do not modify */

/*
 Copyright (C) 2013 Christian Dywan <christian@twotoasts.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include "midori/midori-browser.h"
#include "midori/midori-view.h"
#include "midori/midori-websettings.h"
#include <gtk/gtk.h>
#include "midori-core.h"
#include "webkit/webkit.h"
#include <stdlib.h>
#include <string.h>
#include "midori/midori-app.h"

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_main_context_unref0(var) ((var == NULL) ? NULL : (var = (g_main_context_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);



void actions_view_page (void);
void _vala_main (gchar** args,
                 int args_length1);
static void _actions_view_page_gtest_func (void);


static gpointer
_g_main_context_ref0 (gpointer self)
{
#line 18 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	return self ? g_main_context_ref (self) : NULL;
#line 49 "actions.c"
}


void
actions_view_page (void)
{
	MidoriBrowser* browser = NULL;
	MidoriBrowser* _tmp0_;
	MidoriView* view = NULL;
	MidoriWebSettings* _tmp1_;
	MidoriWebSettings* _tmp2_;
	MidoriView* _tmp3_;
	MidoriView* _tmp4_;
	MidoriBrowser* _tmp5_;
	MidoriView* _tmp6_;
	MidoriBrowser* _tmp7_;
	MidoriView* _tmp8_;
	GMainContext* loop = NULL;
	GMainContext* _tmp9_;
	GMainContext* _tmp10_;
	WebKitHitTestResult* hit_test_result = NULL;
	GObject* _tmp16_;
	GObject* _tmp17_;
	WebKitHitTestResult* _tmp18_;
	MidoriContextAction* menu = NULL;
	MidoriView* _tmp19_;
	WebKitHitTestResult* _tmp20_;
	MidoriContextAction* _tmp21_;
	MidoriContextAction* _tmp22_;
	MidoriContextAction* _tmp23_;
	const gchar* _tmp24_;
	const gchar* _tmp25_;
	MidoriContextAction* _tmp26_;
	GtkAction* _tmp27_;
	GtkAction* _tmp28_;
	WebKitHitTestResult* hit_test_result2 = NULL;
	GObject* _tmp29_;
	GObject* _tmp30_;
	WebKitHitTestResult* _tmp31_;
	MidoriContextAction* menu2 = NULL;
	MidoriView* _tmp32_;
	WebKitHitTestResult* _tmp33_;
	MidoriContextAction* _tmp34_;
	MidoriContextAction* _tmp35_;
	MidoriContextAction* _tmp36_;
	const gchar* _tmp37_;
	const gchar* _tmp38_;
	GtkAction* copy = NULL;
	MidoriContextAction* _tmp39_;
	GtkAction* _tmp40_;
	GtkAction* _tmp41_;
	GtkAction* _tmp42_;
	gboolean _tmp43_;
	gboolean _tmp44_;
	MidoriView* _tmp45_;
	WebKitWebView* _tmp46_;
	WebKitWebView* _tmp47_;
	MidoriView* _tmp48_;
	WebKitHitTestResult* _tmp49_;
	MidoriContextAction* _tmp50_;
	MidoriContextAction* _tmp51_;
	GtkAction* _tmp52_;
	GtkAction* _tmp53_;
	gboolean _tmp54_;
	gboolean _tmp55_;
	MidoriView* _tmp56_;
	GObject* _tmp62_;
	GObject* _tmp63_;
	WebKitHitTestResult* _tmp64_;
	MidoriView* _tmp65_;
	WebKitHitTestResult* _tmp66_;
	MidoriContextAction* _tmp67_;
	MidoriContextAction* _tmp68_;
	GtkAction* _tmp69_;
	GtkAction* _tmp70_;
	gboolean _tmp71_;
	gboolean _tmp72_;
	MidoriView* _tmp73_;
	WebKitWebView* _tmp74_;
	WebKitWebView* _tmp75_;
	MidoriView* _tmp76_;
	WebKitHitTestResult* _tmp77_;
	MidoriContextAction* _tmp78_;
	MidoriContextAction* _tmp79_;
	GtkAction* _tmp80_;
	GtkAction* _tmp81_;
	gboolean _tmp82_;
	gboolean _tmp83_;
#line 13 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp0_ = midori_browser_new ();
#line 13 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	g_object_ref_sink (_tmp0_);
#line 13 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	browser = _tmp0_;
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp1_ = midori_web_settings_new ();
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp2_ = _tmp1_;
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp3_ = (MidoriView*) midori_view_new_with_title (NULL, _tmp2_, FALSE);
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	g_object_ref_sink (_tmp3_);
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp4_ = _tmp3_;
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (_tmp2_);
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	view = _tmp4_;
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp5_ = browser;
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp6_ = view;
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	midori_browser_add_tab (_tmp5_, _tmp6_);
#line 16 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp7_ = browser;
#line 16 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	gtk_widget_show ((GtkWidget*) _tmp7_);
#line 17 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp8_ = view;
#line 17 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	midori_view_set_html (_tmp8_, "<body>The earth is <em>flat</em> for a fact.</body>", NULL, NULL);
#line 18 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp9_ = g_main_context_default ();
#line 18 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp10_ = _g_main_context_ref0 (_tmp9_);
#line 18 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	loop = _tmp10_;
#line 178 "actions.c"
	{
		gboolean _tmp11_ = FALSE;
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
		_tmp11_ = TRUE;
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
		while (TRUE) {
#line 185 "actions.c"
			GMainContext* _tmp15_;
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
			if (!_tmp11_) {
#line 189 "actions.c"
				MidoriView* _tmp12_;
				MidoriLoadStatus _tmp13_;
				MidoriLoadStatus _tmp14_;
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
				_tmp12_ = view;
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
				_tmp13_ = midori_tab_get_load_status ((MidoriTab*) _tmp12_);
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
				_tmp14_ = _tmp13_;
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
				if (!(_tmp14_ != MIDORI_LOAD_FINISHED)) {
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
					break;
#line 203 "actions.c"
				}
			}
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
			_tmp11_ = FALSE;
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
			_tmp15_ = loop;
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
			g_main_context_iteration (_tmp15_, TRUE);
#line 212 "actions.c"
		}
	}
#line 21 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp16_ = g_object_new (WEBKIT_TYPE_HIT_TEST_RESULT, "context", WEBKIT_HIT_TEST_RESULT_CONTEXT_DOCUMENT, NULL);
#line 21 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp17_ = G_IS_INITIALLY_UNOWNED (_tmp16_) ? g_object_ref_sink (_tmp16_) : _tmp16_;
#line 21 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp18_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp17_, WEBKIT_TYPE_HIT_TEST_RESULT) ? ((WebKitHitTestResult*) _tmp17_) : NULL;
#line 21 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	if (_tmp18_ == NULL) {
#line 21 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
		_g_object_unref0 (_tmp17_);
#line 225 "actions.c"
	}
#line 21 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	hit_test_result = _tmp18_;
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp19_ = view;
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp20_ = hit_test_result;
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp21_ = midori_view_get_page_context_action (_tmp19_, _tmp20_);
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	menu = _tmp21_;
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp22_ = menu;
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (_tmp22_ != NULL, "menu != null");
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp23_ = menu;
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp24_ = gtk_action_get_name ((GtkAction*) _tmp23_);
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp25_ = _tmp24_;
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (g_strcmp0 (_tmp25_, "PageContextMenu") == 0, "menu.name == \"PageContextMenu\"");
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp26_ = menu;
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp27_ = midori_context_action_get_by_name (_tmp26_, "Back");
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp28_ = _tmp27_;
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (_tmp28_ != NULL, "menu.get_by_name (\"Back\") != null");
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (_tmp28_);
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp29_ = g_object_new (WEBKIT_TYPE_HIT_TEST_RESULT, "context", WEBKIT_HIT_TEST_RESULT_CONTEXT_EDITABLE, NULL);
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp30_ = G_IS_INITIALLY_UNOWNED (_tmp29_) ? g_object_ref_sink (_tmp29_) : _tmp29_;
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp31_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp30_, WEBKIT_TYPE_HIT_TEST_RESULT) ? ((WebKitHitTestResult*) _tmp30_) : NULL;
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	if (_tmp31_ == NULL) {
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
		_g_object_unref0 (_tmp30_);
#line 269 "actions.c"
	}
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	hit_test_result2 = _tmp31_;
#line 29 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp32_ = view;
#line 29 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp33_ = hit_test_result2;
#line 29 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp34_ = midori_view_get_page_context_action (_tmp32_, _tmp33_);
#line 29 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	menu2 = _tmp34_;
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp35_ = menu2;
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (_tmp35_ != NULL, "menu2 != null");
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp36_ = menu2;
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp37_ = gtk_action_get_name ((GtkAction*) _tmp36_);
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp38_ = _tmp37_;
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (g_strcmp0 (_tmp38_, "PageContextMenu") == 0, "menu2.name == \"PageContextMenu\"");
#line 32 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp39_ = menu2;
#line 32 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp40_ = midori_context_action_get_by_name (_tmp39_, "Copy");
#line 32 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	copy = _tmp40_;
#line 33 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp41_ = copy;
#line 33 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (_tmp41_ != NULL, "copy != null");
#line 34 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp42_ = copy;
#line 34 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp43_ = gtk_action_get_sensitive (_tmp42_);
#line 34 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp44_ = _tmp43_;
#line 34 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (!_tmp44_, "!copy.sensitive");
#line 35 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp45_ = view;
#line 35 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp46_ = midori_tab_get_web_view ((MidoriTab*) _tmp45_);
#line 35 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp47_ = _tmp46_;
#line 35 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (webkit_web_view_search_text (_tmp47_, "flat", TRUE, FALSE, FALSE), "view.web_view.search_text (\"flat\", true, false, false)");
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp48_ = view;
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp49_ = hit_test_result;
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp50_ = midori_view_get_page_context_action (_tmp48_, _tmp49_);
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (menu);
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	menu = _tmp50_;
#line 37 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp51_ = menu;
#line 37 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp52_ = midori_context_action_get_by_name (_tmp51_, "Copy");
#line 37 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (copy);
#line 37 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	copy = _tmp52_;
#line 38 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp53_ = copy;
#line 38 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp54_ = gtk_action_get_sensitive (_tmp53_);
#line 38 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp55_ = _tmp54_;
#line 38 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (_tmp55_, "copy.sensitive");
#line 42 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp56_ = view;
#line 42 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	midori_view_set_html (_tmp56_, "<body>The earth is <em>flat</em> for a fact.</body>", NULL, NULL);
#line 349 "actions.c"
	{
		gboolean _tmp57_ = FALSE;
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
		_tmp57_ = TRUE;
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
		while (TRUE) {
#line 356 "actions.c"
			GMainContext* _tmp61_;
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
			if (!_tmp57_) {
#line 360 "actions.c"
				MidoriView* _tmp58_;
				MidoriLoadStatus _tmp59_;
				MidoriLoadStatus _tmp60_;
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
				_tmp58_ = view;
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
				_tmp59_ = midori_tab_get_load_status ((MidoriTab*) _tmp58_);
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
				_tmp60_ = _tmp59_;
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
				if (!(_tmp60_ != MIDORI_LOAD_FINISHED)) {
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
					break;
#line 374 "actions.c"
				}
			}
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
			_tmp57_ = FALSE;
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
			_tmp61_ = loop;
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
			g_main_context_iteration (_tmp61_, TRUE);
#line 383 "actions.c"
		}
	}
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp62_ = g_object_new (WEBKIT_TYPE_HIT_TEST_RESULT, "context", WEBKIT_HIT_TEST_RESULT_CONTEXT_SELECTION, NULL);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp63_ = G_IS_INITIALLY_UNOWNED (_tmp62_) ? g_object_ref_sink (_tmp62_) : _tmp62_;
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp64_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp63_, WEBKIT_TYPE_HIT_TEST_RESULT) ? ((WebKitHitTestResult*) _tmp63_) : NULL;
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	if (_tmp64_ == NULL) {
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
		_g_object_unref0 (_tmp63_);
#line 396 "actions.c"
	}
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (hit_test_result);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	hit_test_result = _tmp64_;
#line 47 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp65_ = view;
#line 47 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp66_ = hit_test_result;
#line 47 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp67_ = midori_view_get_page_context_action (_tmp65_, _tmp66_);
#line 47 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (menu);
#line 47 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	menu = _tmp67_;
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp68_ = menu;
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp69_ = midori_context_action_get_by_name (_tmp68_, "Copy");
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (copy);
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	copy = _tmp69_;
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp70_ = copy;
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp71_ = gtk_action_get_sensitive (_tmp70_);
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp72_ = _tmp71_;
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (!_tmp72_, "!copy.sensitive");
#line 50 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp73_ = view;
#line 50 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp74_ = midori_tab_get_web_view ((MidoriTab*) _tmp73_);
#line 50 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp75_ = _tmp74_;
#line 50 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (webkit_web_view_search_text (_tmp75_, "flat", TRUE, FALSE, FALSE), "view.web_view.search_text (\"flat\", true, false, false)");
#line 51 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp76_ = view;
#line 51 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp77_ = hit_test_result;
#line 51 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp78_ = midori_view_get_page_context_action (_tmp76_, _tmp77_);
#line 51 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (menu);
#line 51 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	menu = _tmp78_;
#line 52 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp79_ = menu;
#line 52 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp80_ = midori_context_action_get_by_name (_tmp79_, "Copy");
#line 52 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (copy);
#line 52 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	copy = _tmp80_;
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp81_ = copy;
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp82_ = gtk_action_get_sensitive (_tmp81_);
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp83_ = _tmp82_;
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_assert (_tmp83_, "copy.sensitive");
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (copy);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (menu2);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (hit_test_result2);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (menu);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (hit_test_result);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_main_context_unref0 (loop);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (view);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_g_object_unref0 (browser);
#line 478 "actions.c"
}


static void
_actions_view_page_gtest_func (void)
{
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	actions_view_page ();
#line 487 "actions.c"
}


void
_vala_main (gchar** args,
            int args_length1)
{
	SoupSession* _tmp0_;
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	g_test_init (&args_length1, &args, NULL);
#line 59 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	midori_app_setup (&args_length1, &args, NULL);
#line 60 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	midori_paths_init (MIDORI_RUNTIME_MODE_NORMAL, NULL);
#line 62 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_tmp0_ = webkit_get_default_session ();
#line 62 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	g_object_set_data_full ((GObject*) _tmp0_, "midori-session-initialized", (gpointer) ((gintptr) TRUE), NULL);
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	g_test_add_func ("/actions/view/page", _actions_view_page_gtest_func);
#line 65 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	g_test_run ();
#line 510 "actions.c"
}


int
main (int argc,
      char ** argv)
{
#line 57 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	_vala_main (argv, argc);
#line 57 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/actions.vala"
	return 0;
#line 522 "actions.c"
}



