/* app.c generated by valac 0.40.4, the Vala compiler
 * generated from app.vala, do not modify */

/*
 Copyright (C) 2012 Christian Dywan <christian@twotoasts.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include "midori/midori-websettings.h"
#include <gdk/gdk.h>
#include "midori-core.h"
#include <float.h>
#include <math.h>
#include "midori/midori-app.h"
#include "midori/midori-view.h"
#include "midori/midori-browser.h"
#include <stdlib.h>
#include <string.h>
#include <glib/gstdio.h>
#include "midori/midori-frontend.h"

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_main_context_unref0(var) ((var == NULL) ? NULL : (var = (g_main_context_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);



gboolean check_sensible_window_size (GtkWindow* window,
                                     MidoriWebSettings* settings);
void app_normal (void);
void app_normal_custom_config (void);
void app_private (void);
void app_web (void);
void app_web_custom_config (void);
void _vala_main (gchar** args,
                 int args_length1);
static void _app_normal_gtest_func (void);
static void _app_normal_custom_config_gtest_func (void);
static void _app_private_gtest_func (void);
static void _app_web_gtest_func (void);
static void _app_web_custom_config_gtest_func (void);


gboolean
check_sensible_window_size (GtkWindow* window,
                            MidoriWebSettings* settings)
{
	gboolean result = FALSE;
	GdkRectangle monitor = {0};
	GdkScreen* _tmp0_;
	GdkScreen* _tmp1_;
	GdkRectangle _tmp2_ = {0};
	gboolean _tmp3_ = FALSE;
	gint _tmp4_;
	gint _tmp5_;
	GdkRectangle _tmp6_;
	gint _tmp7_;
#line 12 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_return_val_if_fail (window != NULL, FALSE);
#line 12 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_return_val_if_fail (settings != NULL, FALSE);
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp0_ = gtk_window_get_screen (window);
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp1_ = _tmp0_;
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	gdk_screen_get_monitor_geometry (_tmp1_, 0, &_tmp2_);
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	monitor = _tmp2_;
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp4_ = midori_settings_get_last_window_width ((MidoriSettings*) settings);
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp5_ = _tmp4_;
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp6_ = monitor;
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp7_ = _tmp6_.width;
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	if (((gdouble) (_tmp5_ + 1)) >= (_tmp7_ / 1.7)) {
#line 96 "app.c"
		gint _tmp8_;
		gint _tmp9_;
		GdkRectangle _tmp10_;
		gint _tmp11_;
#line 16 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp8_ = midori_settings_get_last_window_height ((MidoriSettings*) settings);
#line 16 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp9_ = _tmp8_;
#line 16 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp10_ = monitor;
#line 16 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp11_ = _tmp10_.height;
#line 16 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp3_ = ((gdouble) (_tmp9_ + 1)) >= (_tmp11_ / 1.7);
#line 111 "app.c"
	} else {
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp3_ = FALSE;
#line 115 "app.c"
	}
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	result = _tmp3_;
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	return result;
#line 121 "app.c"
}


static gpointer
_g_object_ref0 (gpointer self)
{
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	return self ? g_object_ref (self) : NULL;
#line 130 "app.c"
}


static gpointer
_g_main_context_ref0 (gpointer self)
{
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	return self ? g_main_context_ref (self) : NULL;
#line 139 "app.c"
}


void
app_normal (void)
{
	MidoriApp* app = NULL;
	MidoriApp* _tmp0_;
	MidoriApp* _tmp1_;
	GMainContext* loop = NULL;
	GMainContext* _tmp2_;
	GMainContext* _tmp3_;
	MidoriApp* _tmp24_;
#line 20 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_test_grab_max_timeout ();
#line 21 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_test_idle_timeouts ();
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_test_log_set_fatal_handler_for_icons ();
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_paths_test_reset_runtime_mode ();
#line 24 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_app_set_instance_is_running (FALSE);
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp0_ = midori_normal_app_new (NULL, "test-normal", FALSE, NULL, NULL, -1, NULL);
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	app = _tmp1_;
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp2_ = g_main_context_default ();
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp3_ = _g_main_context_ref0 (_tmp2_);
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	loop = _tmp3_;
#line 175 "app.c"
	{
		gboolean _tmp4_ = FALSE;
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp4_ = TRUE;
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		while (TRUE) {
#line 182 "app.c"
			GMainContext* _tmp8_;
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			if (!_tmp4_) {
#line 186 "app.c"
				MidoriApp* _tmp5_;
				MidoriBrowser* _tmp6_;
				MidoriBrowser* _tmp7_;
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp5_ = app;
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp6_ = midori_app_get_browser (_tmp5_);
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp7_ = _tmp6_;
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				if (!(_tmp7_ == NULL)) {
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
					break;
#line 200 "app.c"
				}
			}
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			_tmp4_ = FALSE;
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			_tmp8_ = loop;
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			g_main_context_iteration (_tmp8_, TRUE);
#line 209 "app.c"
		}
	}
	{
		gint i = 0;
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		i = 0;
#line 216 "app.c"
		{
			gboolean _tmp9_ = FALSE;
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			_tmp9_ = TRUE;
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			while (TRUE) {
#line 223 "app.c"
				gint _tmp11_;
				MidoriView* tab = NULL;
				MidoriApp* _tmp12_;
				MidoriBrowser* _tmp13_;
				MidoriBrowser* _tmp14_;
				GtkWidget* _tmp15_;
				MidoriView* _tmp16_;
				MidoriApp* _tmp17_;
				MidoriBrowser* _tmp18_;
				MidoriBrowser* _tmp19_;
				MidoriView* _tmp20_;
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				if (!_tmp9_) {
#line 237 "app.c"
					gint _tmp10_;
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
					_tmp10_ = i;
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
					i = _tmp10_ + 1;
#line 243 "app.c"
				}
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp9_ = FALSE;
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp11_ = i;
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				if (!(_tmp11_ < 3)) {
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
					break;
#line 253 "app.c"
				}
#line 29 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp12_ = app;
#line 29 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp13_ = midori_app_get_browser (_tmp12_);
#line 29 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp14_ = _tmp13_;
#line 29 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp15_ = midori_browser_add_uri (_tmp14_, "about:blank");
#line 29 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp16_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp15_, MIDORI_TYPE_VIEW) ? ((MidoriView*) _tmp15_) : NULL);
#line 29 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				tab = _tmp16_;
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp17_ = app;
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp18_ = midori_app_get_browser (_tmp17_);
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp19_ = _tmp18_;
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp20_ = tab;
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				midori_browser_close_tab (_tmp19_, _tmp20_);
#line 277 "app.c"
				{
					gboolean _tmp21_ = FALSE;
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
					_tmp21_ = TRUE;
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
					while (TRUE) {
#line 284 "app.c"
						GMainContext* _tmp23_;
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
						if (!_tmp21_) {
#line 288 "app.c"
							GMainContext* _tmp22_;
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
							_tmp22_ = loop;
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
							if (!g_main_context_pending (_tmp22_)) {
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
								break;
#line 296 "app.c"
							}
						}
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
						_tmp21_ = FALSE;
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
						_tmp23_ = loop;
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
						g_main_context_iteration (_tmp23_, TRUE);
#line 305 "app.c"
					}
				}
#line 28 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_g_object_unref0 (tab);
#line 310 "app.c"
			}
		}
	}
#line 33 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp24_ = app;
#line 33 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_normal_app_on_quit (_tmp24_);
#line 34 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_test_release_max_timeout ();
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_main_context_unref0 (loop);
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_object_unref0 (app);
#line 324 "app.c"
}


void
app_normal_custom_config (void)
{
	gchar* config_dir = NULL;
	MidoriApp* app = NULL;
	const gchar* _tmp4_;
	MidoriApp* _tmp5_;
	MidoriApp* _tmp6_;
	GError * _inner_error_ = NULL;
#line 38 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_test_grab_max_timeout ();
#line 39 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_test_idle_timeouts ();
#line 40 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_test_log_set_fatal_handler_for_icons ();
#line 41 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_paths_test_reset_runtime_mode ();
#line 42 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_app_set_instance_is_running (FALSE);
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	config_dir = NULL;
#line 349 "app.c"
	{
		gchar* _tmp0_ = NULL;
		gchar* _tmp1_;
		gchar* _tmp2_;
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp1_ = g_dir_make_tmp ("custom-configXXXXXX", &_inner_error_);
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp0_ = _tmp1_;
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 360 "app.c"
			goto __catch0_g_error;
		}
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp2_ = _tmp0_;
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp0_ = NULL;
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_g_free0 (config_dir);
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		config_dir = _tmp2_;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_g_free0 (_tmp0_);
#line 373 "app.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* _error_ = NULL;
		const gchar* _tmp3_;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_error_ = _inner_error_;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_inner_error_ = NULL;
#line 47 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp3_ = _error_->message;
#line 47 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		g_error ("app.vala:47: %s", _tmp3_);
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_g_error_free0 (_error_);
#line 390 "app.c"
	}
	__finally0:
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_g_free0 (config_dir);
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		g_clear_error (&_inner_error_);
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		return;
#line 403 "app.c"
	}
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp4_ = config_dir;
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp5_ = midori_normal_app_new (_tmp4_, "test-custom-config-normal", FALSE, NULL, NULL, -1, NULL);
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp6_ = _g_object_ref0 (_tmp5_);
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	app = _tmp6_;
#line 51 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_normal_app_on_quit (app);
#line 52 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_test_release_max_timeout ();
#line 37 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_object_unref0 (app);
#line 37 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_free0 (config_dir);
#line 421 "app.c"
}


void
app_private (void)
{
	MidoriBrowser* browser = NULL;
	MidoriBrowser* _tmp0_;
	MidoriBrowser* _tmp1_;
	GMainContext* loop = NULL;
	GMainContext* _tmp2_;
	GMainContext* _tmp3_;
	MidoriBrowser* _tmp7_;
	MidoriBrowser* _tmp8_;
	MidoriWebSettings* _tmp9_;
	MidoriWebSettings* _tmp10_;
	MidoriWebSettings* _tmp11_;
#line 56 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_test_log_set_fatal_handler_for_icons ();
#line 57 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_paths_test_reset_runtime_mode ();
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_app_set_instance_is_running (FALSE);
#line 59 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp0_ = midori_private_app_new (NULL, NULL, NULL, NULL, -1, NULL);
#line 59 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 59 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	browser = _tmp1_;
#line 60 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp2_ = g_main_context_default ();
#line 60 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp3_ = _g_main_context_ref0 (_tmp2_);
#line 60 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	loop = _tmp3_;
#line 457 "app.c"
	{
		gboolean _tmp4_ = FALSE;
#line 61 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp4_ = TRUE;
#line 61 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		while (TRUE) {
#line 464 "app.c"
			GMainContext* _tmp6_;
#line 61 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			if (!_tmp4_) {
#line 468 "app.c"
				GMainContext* _tmp5_;
#line 61 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp5_ = loop;
#line 61 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				if (!g_main_context_pending (_tmp5_)) {
#line 61 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
					break;
#line 476 "app.c"
				}
			}
#line 61 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			_tmp4_ = FALSE;
#line 61 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			_tmp6_ = loop;
#line 61 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			g_main_context_iteration (_tmp6_, TRUE);
#line 485 "app.c"
		}
	}
#line 62 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp7_ = browser;
#line 62 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp8_ = browser;
#line 62 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_object_get (_tmp8_, "settings", &_tmp9_, NULL);
#line 62 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp10_ = _tmp9_;
#line 62 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp11_ = _tmp10_;
#line 62 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_vala_assert (check_sensible_window_size ((GtkWindow*) _tmp7_, _tmp11_), "check_sensible_window_size (browser, browser.settings)");
#line 62 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_object_unref0 (_tmp11_);
#line 55 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_main_context_unref0 (loop);
#line 55 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_object_unref0 (browser);
#line 506 "app.c"
}


void
app_web (void)
{
	MidoriBrowser* browser = NULL;
	MidoriBrowser* _tmp0_;
	MidoriBrowser* _tmp1_;
	GMainContext* loop = NULL;
	GMainContext* _tmp2_;
	GMainContext* _tmp3_;
	MidoriBrowser* _tmp7_;
	MidoriBrowser* _tmp8_;
	MidoriWebSettings* _tmp9_;
	MidoriWebSettings* _tmp10_;
	MidoriWebSettings* _tmp11_;
#line 66 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_paths_test_reset_runtime_mode ();
#line 67 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_app_set_instance_is_running (FALSE);
#line 68 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp0_ = midori_web_app_new ("https://mail.google.com", NULL, NULL, -1, NULL);
#line 68 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 68 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	browser = _tmp1_;
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp2_ = g_main_context_default ();
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp3_ = _g_main_context_ref0 (_tmp2_);
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	loop = _tmp3_;
#line 540 "app.c"
	{
		gboolean _tmp4_ = FALSE;
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp4_ = TRUE;
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		while (TRUE) {
#line 547 "app.c"
			GMainContext* _tmp6_;
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			if (!_tmp4_) {
#line 551 "app.c"
				GMainContext* _tmp5_;
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp5_ = loop;
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				if (!g_main_context_pending (_tmp5_)) {
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
					break;
#line 559 "app.c"
				}
			}
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			_tmp4_ = FALSE;
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			_tmp6_ = loop;
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			g_main_context_iteration (_tmp6_, TRUE);
#line 568 "app.c"
		}
	}
#line 71 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp7_ = browser;
#line 71 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp8_ = browser;
#line 71 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_object_get (_tmp8_, "settings", &_tmp9_, NULL);
#line 71 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp10_ = _tmp9_;
#line 71 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp11_ = _tmp10_;
#line 71 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_vala_assert (check_sensible_window_size ((GtkWindow*) _tmp7_, _tmp11_), "check_sensible_window_size (browser, browser.settings)");
#line 71 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_object_unref0 (_tmp11_);
#line 65 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_main_context_unref0 (loop);
#line 65 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_object_unref0 (browser);
#line 589 "app.c"
}


void
app_web_custom_config (void)
{
	MidoriBrowser* browser = NULL;
	MidoriBrowser* _tmp0_;
	MidoriBrowser* _tmp1_;
	GMainContext* loop = NULL;
	GMainContext* _tmp2_;
	GMainContext* _tmp3_;
	MidoriBrowser* _tmp7_;
	MidoriBrowser* _tmp8_;
	MidoriWebSettings* _tmp9_;
	MidoriWebSettings* _tmp10_;
	MidoriWebSettings* _tmp11_;
#line 75 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_paths_test_reset_runtime_mode ();
#line 76 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_app_set_instance_is_running (FALSE);
#line 77 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp0_ = midori_web_app_new ("https://mail.google.com", NULL, NULL, -1, NULL);
#line 77 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 77 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	browser = _tmp1_;
#line 78 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp2_ = g_main_context_default ();
#line 78 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp3_ = _g_main_context_ref0 (_tmp2_);
#line 78 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	loop = _tmp3_;
#line 623 "app.c"
	{
		gboolean _tmp4_ = FALSE;
#line 79 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		_tmp4_ = TRUE;
#line 79 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
		while (TRUE) {
#line 630 "app.c"
			GMainContext* _tmp6_;
#line 79 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			if (!_tmp4_) {
#line 634 "app.c"
				GMainContext* _tmp5_;
#line 79 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				_tmp5_ = loop;
#line 79 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
				if (!g_main_context_pending (_tmp5_)) {
#line 79 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
					break;
#line 642 "app.c"
				}
			}
#line 79 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			_tmp4_ = FALSE;
#line 79 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			_tmp6_ = loop;
#line 79 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
			g_main_context_iteration (_tmp6_, TRUE);
#line 651 "app.c"
		}
	}
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp7_ = browser;
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp8_ = browser;
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_object_get (_tmp8_, "settings", &_tmp9_, NULL);
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp10_ = _tmp9_;
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_tmp11_ = _tmp10_;
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_vala_assert (check_sensible_window_size ((GtkWindow*) _tmp7_, _tmp11_), "check_sensible_window_size (browser, browser.settings)");
#line 80 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_object_unref0 (_tmp11_);
#line 74 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_main_context_unref0 (loop);
#line 74 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_g_object_unref0 (browser);
#line 672 "app.c"
}


static void
_app_normal_gtest_func (void)
{
#line 86 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	app_normal ();
#line 681 "app.c"
}


static void
_app_normal_custom_config_gtest_func (void)
{
#line 87 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	app_normal_custom_config ();
#line 690 "app.c"
}


static void
_app_private_gtest_func (void)
{
#line 88 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	app_private ();
#line 699 "app.c"
}


static void
_app_web_gtest_func (void)
{
#line 89 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	app_web ();
#line 708 "app.c"
}


static void
_app_web_custom_config_gtest_func (void)
{
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	app_web_custom_config ();
#line 717 "app.c"
}


void
_vala_main (gchar** args,
            int args_length1)
{
#line 84 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_test_init (&args_length1, &args, NULL);
#line 85 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	midori_app_setup (&args_length1, &args, NULL);
#line 86 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_test_add_func ("/app/normal", _app_normal_gtest_func);
#line 87 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_test_add_func ("/app/normal-custom-config", _app_normal_custom_config_gtest_func);
#line 88 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_test_add_func ("/app/private", _app_private_gtest_func);
#line 89 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_test_add_func ("/app/web", _app_web_gtest_func);
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_test_add_func ("/app/web-custom-config", _app_web_custom_config_gtest_func);
#line 91 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	g_test_run ();
#line 741 "app.c"
}


int
main (int argc,
      char ** argv)
{
#line 83 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	_vala_main (argv, argc);
#line 83 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/app.vala"
	return 0;
#line 753 "app.c"
}



