/* speeddial.c generated by valac 0.40.4, the Vala compiler
 * generated from speeddial.vala, do not modify */

/*
 Copyright (C) 2012 Christian Dywan <christian@twotoasts.de>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include "midori-core.h"
#include <glib/gstdio.h>
#include "midori/midori-app.h"

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))


extern gchar* tmp_folder;
gchar* tmp_folder = NULL;

gchar* get_test_file (const gchar* contents);
void speeddial_load (void);
void _vala_main (gchar** args,
                 int args_length1);
static void _speeddial_load_gtest_func (void);


gchar*
get_test_file (const gchar* contents)
{
	gchar* result = NULL;
	const gchar* _tmp0_;
	gchar* checksum = NULL;
	gchar* _tmp2_;
	gchar* file = NULL;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	GError * _inner_error_ = NULL;
#line 12 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	g_return_val_if_fail (contents != NULL, NULL);
#line 13 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp0_ = tmp_folder;
#line 13 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	if (_tmp0_ == NULL) {
#line 57 "speeddial.c"
		gchar* _tmp1_;
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp1_ = midori_paths_make_tmp_dir ("speeddialXXXXXX");
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (tmp_folder);
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		tmp_folder = _tmp1_;
#line 65 "speeddial.c"
	}
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp2_ = g_compute_checksum_for_string (G_CHECKSUM_MD5, contents, (gsize) -1);
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	checksum = _tmp2_;
#line 16 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp3_ = tmp_folder;
#line 16 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp4_ = g_build_path (G_DIR_SEPARATOR_S, _tmp3_, checksum, NULL);
#line 16 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	file = _tmp4_;
#line 77 "speeddial.c"
	{
#line 18 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_file_set_contents (file, contents, (gssize) -1, &_inner_error_);
#line 18 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 83 "speeddial.c"
			goto __catch0_g_error;
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* file_error = NULL;
		const gchar* _tmp5_;
#line 17 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		file_error = _inner_error_;
#line 17 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_inner_error_ = NULL;
#line 20 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp5_ = file_error->message;
#line 20 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_error ("speeddial.vala:20: %s", _tmp5_);
#line 17 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_error_free0 (file_error);
#line 102 "speeddial.c"
	}
	__finally0:
#line 17 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 17 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (file);
#line 17 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (checksum);
#line 17 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 17 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_clear_error (&_inner_error_);
#line 17 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		return NULL;
#line 117 "speeddial.c"
	}
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	result = file;
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_g_free0 (checksum);
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	return result;
#line 125 "speeddial.c"
}


void
speeddial_load (void)
{
	gchar* data = NULL;
	gchar* _tmp0_;
	gchar* json = NULL;
	gchar* _tmp1_;
	MidoriSpeedDial* dial_data = NULL;
	const gchar* _tmp2_;
	MidoriSpeedDial* _tmp3_;
	MidoriSpeedDial* dial_json = NULL;
	MidoriSpeedDial* _tmp4_;
	const gchar* _tmp5_;
	MidoriSpeedDial* _tmp6_;
	GKeyFile* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	GKeyFile* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	MidoriSpeedDial* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp39_;
	const gchar* _tmp40_;
	MidoriSpeedDial* _tmp41_;
	const gchar* _tmp42_;
	GError * _inner_error_ = NULL;
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp0_ = get_test_file ("\n" \
"            [Dial 1]\n" \
"            uri=http://example.com\n" \
"            title=Example\n" \
"            [settings]\n" \
"            columns=3\n" \
"            rows=3\n" \
"        ");
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	data = _tmp0_;
#line 35 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp1_ = get_test_file ("\n" \
"            '{\"shortcuts\":[{\"id\":\"s1\",\"href\":\"http://example." \
"com\",\"title\":\"Example\",\"img\":\"a2F0emU=\"}]}'\n" \
"        ");
#line 35 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	json = _tmp1_;
#line 39 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp2_ = data;
#line 39 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp3_ = midori_speed_dial_new (_tmp2_, "");
#line 39 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	dial_data = _tmp3_;
#line 40 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp4_ = midori_speed_dial_new ("", json);
#line 40 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	dial_json = _tmp4_;
#line 41 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp5_ = data;
#line 41 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	g_remove (_tmp5_);
#line 42 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	g_remove (json);
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp6_ = dial_data;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp7_ = _tmp6_->keyfile;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp8_ = g_key_file_to_data (_tmp7_, NULL, NULL);
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp9_ = _tmp8_;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp10_ = dial_json->keyfile;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp11_ = g_key_file_to_data (_tmp10_, NULL, NULL);
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp12_ = _tmp11_;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	katze_assert_str_equal (json, _tmp9_, _tmp12_);
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_g_free0 (_tmp12_);
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_g_free0 (_tmp9_);
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp13_ = dial_data;
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp14_ = midori_speed_dial_get_next_free_slot (_tmp13_, NULL);
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp15_ = _tmp14_;
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	katze_assert_str_equal (json, _tmp15_, "Dial 2");
#line 45 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_g_free0 (_tmp15_);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp16_ = midori_speed_dial_get_next_free_slot (dial_json, NULL);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp17_ = _tmp16_;
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	katze_assert_str_equal (json, _tmp17_, "Dial 2");
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_g_free0 (_tmp17_);
#line 221 "speeddial.c"
	{
		MidoriSpeedDial* _tmp18_;
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp18_ = dial_data;
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		midori_speed_dial_save_message (_tmp18_, "SpeedDial", &_inner_error_);
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 230 "speeddial.c"
			goto __catch1_g_error;
		}
#line 50 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_assert_not_reached ();
#line 235 "speeddial.c"
	}
	goto __finally1;
	__catch1_g_error:
	{
		GError* _error_ = NULL;
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_error_ = _inner_error_;
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_inner_error_ = NULL;
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_error_free0 (_error_);
#line 247 "speeddial.c"
	}
	__finally1:
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_object_unref0 (dial_json);
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_object_unref0 (dial_data);
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (json);
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (data);
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_clear_error (&_inner_error_);
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		return;
#line 266 "speeddial.c"
	}
	{
		MidoriSpeedDial* _tmp19_;
#line 54 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp19_ = dial_data;
#line 54 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		midori_speed_dial_save_message (_tmp19_, "speed_dial-save-rename ", &_inner_error_);
#line 54 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 276 "speeddial.c"
			goto __catch2_g_error;
		}
#line 55 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_assert_not_reached ();
#line 281 "speeddial.c"
	}
	goto __finally2;
	__catch2_g_error:
	{
		GError* _error_ = NULL;
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_error_ = _inner_error_;
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_inner_error_ = NULL;
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_error_free0 (_error_);
#line 293 "speeddial.c"
	}
	__finally2:
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_object_unref0 (dial_json);
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_object_unref0 (dial_data);
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (json);
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (data);
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_clear_error (&_inner_error_);
#line 53 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		return;
#line 312 "speeddial.c"
	}
	{
		MidoriSpeedDial* _tmp20_;
#line 59 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp20_ = dial_data;
#line 59 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		midori_speed_dial_save_message (_tmp20_, "speed_dial-save-foo 1", &_inner_error_);
#line 59 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 322 "speeddial.c"
			goto __catch3_g_error;
		}
#line 60 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_assert_not_reached ();
#line 327 "speeddial.c"
	}
	goto __finally3;
	__catch3_g_error:
	{
		GError* _error_ = NULL;
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_error_ = _inner_error_;
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_inner_error_ = NULL;
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_error_free0 (_error_);
#line 339 "speeddial.c"
	}
	__finally3:
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_object_unref0 (dial_json);
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_object_unref0 (dial_data);
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (json);
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (data);
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_clear_error (&_inner_error_);
#line 58 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		return;
#line 358 "speeddial.c"
	}
	{
		MidoriSpeedDial* _tmp21_;
		gchar* _tmp22_ = NULL;
		MidoriSpeedDial* _tmp23_;
		GKeyFile* _tmp24_;
		gchar* _tmp25_;
		const gchar* _tmp26_;
		MidoriSpeedDial* _tmp27_;
		gchar* _tmp28_ = NULL;
		MidoriSpeedDial* _tmp29_;
		GKeyFile* _tmp30_;
		gchar* _tmp31_;
		const gchar* _tmp32_;
		MidoriSpeedDial* _tmp33_;
		const gchar* _tmp34_;
		MidoriSpeedDial* _tmp35_;
		gchar* _tmp36_;
		gchar* _tmp37_;
#line 65 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp21_ = dial_data;
#line 65 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		midori_speed_dial_save_message (_tmp21_, "speed_dial-save-rename 1 Lorem", &_inner_error_);
#line 65 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 384 "speeddial.c"
			goto __catch4_g_error;
		}
#line 66 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp23_ = dial_data;
#line 66 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp24_ = _tmp23_->keyfile;
#line 66 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp25_ = g_key_file_get_string (_tmp24_, "Dial 1", "title", &_inner_error_);
#line 66 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp22_ = _tmp25_;
#line 66 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 397 "speeddial.c"
			goto __catch4_g_error;
		}
#line 66 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp26_ = data;
#line 66 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		katze_assert_str_equal (_tmp26_, _tmp22_, "Lorem");
#line 67 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp27_ = dial_data;
#line 67 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		midori_speed_dial_save_message (_tmp27_, "speed_dial-save-rename 1 Lorem Ipsum Dolomit", &_inner_error_);
#line 67 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 67 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
			_g_free0 (_tmp22_);
#line 412 "speeddial.c"
			goto __catch4_g_error;
		}
#line 68 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp29_ = dial_data;
#line 68 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp30_ = _tmp29_->keyfile;
#line 68 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp31_ = g_key_file_get_string (_tmp30_, "Dial 1", "title", &_inner_error_);
#line 68 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp28_ = _tmp31_;
#line 68 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 68 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
			_g_free0 (_tmp22_);
#line 427 "speeddial.c"
			goto __catch4_g_error;
		}
#line 68 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp32_ = data;
#line 68 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		katze_assert_str_equal (_tmp32_, _tmp28_, "Lorem Ipsum Dolomit");
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp33_ = dial_data;
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		midori_speed_dial_save_message (_tmp33_, "speed_dial-save-delete 1", &_inner_error_);
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
			_g_free0 (_tmp28_);
#line 69 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
			_g_free0 (_tmp22_);
#line 444 "speeddial.c"
			goto __catch4_g_error;
		}
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp34_ = data;
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp35_ = dial_data;
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp36_ = midori_speed_dial_get_next_free_slot (_tmp35_, NULL);
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp37_ = _tmp36_;
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		katze_assert_str_equal (_tmp34_, _tmp37_, "Dial 1");
#line 70 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (_tmp37_);
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (_tmp28_);
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (_tmp22_);
#line 463 "speeddial.c"
	}
	goto __finally4;
	__catch4_g_error:
	{
		GError* message_error = NULL;
		const gchar* _tmp38_;
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		message_error = _inner_error_;
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_inner_error_ = NULL;
#line 72 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp38_ = message_error->message;
#line 72 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_error ("speeddial.vala:72: %s", _tmp38_);
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_error_free0 (message_error);
#line 480 "speeddial.c"
	}
	__finally4:
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_object_unref0 (dial_json);
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_object_unref0 (dial_data);
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (json);
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (data);
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_clear_error (&_inner_error_);
#line 64 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		return;
#line 499 "speeddial.c"
	}
#line 75 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp39_ = get_test_file ("\n" \
"            [settings]\n" \
"            columns=3\n" \
"            rows=3\n" \
"\n" \
"            [Dial 2]\n" \
"            uri=http://green.cat\n" \
"            title=Green cat is green\n" \
"\n" \
"            [Dial 4]\n" \
"            uri=http://heise.de\n" \
"            title=IT-News\n" \
"        ");
#line 75 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_g_free0 (data);
#line 75 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	data = _tmp39_;
#line 88 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp40_ = data;
#line 88 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp41_ = midori_speed_dial_new (_tmp40_, "");
#line 88 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_g_object_unref0 (dial_data);
#line 88 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	dial_data = _tmp41_;
#line 89 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_tmp42_ = data;
#line 89 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	g_remove (_tmp42_);
#line 519 "speeddial.c"
	{
		const gchar* _tmp43_;
		MidoriSpeedDial* _tmp44_;
		gchar* _tmp45_;
		gchar* _tmp46_;
		MidoriSpeedDial* _tmp47_;
		gchar* _tmp48_ = NULL;
		MidoriSpeedDial* _tmp49_;
		GKeyFile* _tmp50_;
		gchar* _tmp51_;
		const gchar* _tmp52_;
#line 91 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp43_ = data;
#line 91 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp44_ = dial_data;
#line 91 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp45_ = midori_speed_dial_get_next_free_slot (_tmp44_, NULL);
#line 91 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp46_ = _tmp45_;
#line 91 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		katze_assert_str_equal (_tmp43_, _tmp46_, "Dial 1");
#line 91 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (_tmp46_);
#line 92 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp47_ = dial_data;
#line 92 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		midori_speed_dial_save_message (_tmp47_, "speed_dial-save-swap 2 4", &_inner_error_);
#line 92 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 549 "speeddial.c"
			goto __catch5_g_error;
		}
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp49_ = dial_data;
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp50_ = _tmp49_->keyfile;
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp51_ = g_key_file_get_string (_tmp50_, "Dial 2", "title", &_inner_error_);
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp48_ = _tmp51_;
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 562 "speeddial.c"
			goto __catch5_g_error;
		}
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp52_ = data;
#line 93 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		katze_assert_str_equal (_tmp52_, _tmp48_, "IT-News");
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (_tmp48_);
#line 571 "speeddial.c"
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* message_error = NULL;
		const gchar* _tmp53_;
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		message_error = _inner_error_;
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_inner_error_ = NULL;
#line 95 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_tmp53_ = message_error->message;
#line 95 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_error ("speeddial.vala:95: %s", _tmp53_);
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_error_free0 (message_error);
#line 588 "speeddial.c"
	}
	__finally5:
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_object_unref0 (dial_json);
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_object_unref0 (dial_data);
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (json);
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		_g_free0 (data);
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		g_clear_error (&_inner_error_);
#line 90 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
		return;
#line 607 "speeddial.c"
	}
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_g_object_unref0 (dial_json);
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_g_object_unref0 (dial_data);
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_g_free0 (json);
#line 25 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_g_free0 (data);
#line 617 "speeddial.c"
}


static void
_speeddial_load_gtest_func (void)
{
#line 103 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	speeddial_load ();
#line 626 "speeddial.c"
}


void
_vala_main (gchar** args,
            int args_length1)
{
#line 100 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	g_test_init (&args_length1, &args, NULL);
#line 101 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	midori_app_setup (&args_length1, &args, NULL);
#line 102 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	midori_paths_init (MIDORI_RUNTIME_MODE_NORMAL, NULL);
#line 103 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	g_test_add_func ("/speeddial/load", _speeddial_load_gtest_func);
#line 104 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	g_test_run ();
#line 644 "speeddial.c"
}


int
main (int argc,
      char ** argv)
{
#line 99 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	_vala_main (argv, argc);
#line 99 "/home/midiba/Documents/glibc/pvd-aware-app/midori/tests/speeddial.vala"
	return 0;
#line 656 "speeddial.c"
}



