/* filter.c generated by valac 0.40.4, the Vala compiler
 * generated from filter.vala, do not modify */

/*
 Copyright (C) 2009-2014 Christian Dywan <christian@twotoasts.de>
 Copyright (C) 2009-2012 Alexander Butenko <a.butenka@gmail.com>

 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.

 See the file COPYING for the full license text.
*/


#include <glib.h>
#include <glib-object.h>
#include "toolbar-editor.h"
#include <stdlib.h>
#include <string.h>

enum  {
	ADBLOCK_FILTER_0_PROPERTY,
	ADBLOCK_FILTER_NUM_PROPERTIES
};
static GParamSpec* adblock_filter_properties[ADBLOCK_FILTER_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_hash_table_unref0(var) ((var == NULL) ? NULL : (var = (g_hash_table_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _AdblockFilterPrivate {
	AdblockOptions* optslist;
};


static gpointer adblock_filter_parent_class = NULL;

#define ADBLOCK_FILTER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ADBLOCK_TYPE_FILTER, AdblockFilterPrivate))
static void adblock_filter_real_insert (AdblockFilter* self,
                                 const gchar* sig,
                                 GRegex* regex);
static GRegex* adblock_filter_real_lookup (AdblockFilter* self,
                                    const gchar* sig);
static guint adblock_filter_real_size (AdblockFilter* self);
static void adblock_filter_real_clear (AdblockFeature* base);
static void _g_free0_ (gpointer var);
static void _g_regex_unref0_ (gpointer var);
void adblock_debug (const gchar* format,
                    ...);
static void adblock_filter_finalize (GObject * obj);


static gpointer
_g_regex_ref0 (gpointer self)
{
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	return self ? g_regex_ref (self) : NULL;
#line 60 "filter.c"
}


static void
adblock_filter_real_insert (AdblockFilter* self,
                            const gchar* sig,
                            GRegex* regex)
{
	GHashTable* _tmp0_;
	gchar* _tmp1_;
	GRegex* _tmp2_;
#line 18 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_if_fail (sig != NULL);
#line 18 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_if_fail (regex != NULL);
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp0_ = self->rules;
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp1_ = g_strdup (sig);
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp2_ = _g_regex_ref0 (regex);
#line 19 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_hash_table_insert (_tmp0_, _tmp1_, _tmp2_);
#line 84 "filter.c"
}


void
adblock_filter_insert (AdblockFilter* self,
                       const gchar* sig,
                       GRegex* regex)
{
#line 18 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_if_fail (self != NULL);
#line 18 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	ADBLOCK_FILTER_GET_CLASS (self)->insert (self, sig, regex);
#line 97 "filter.c"
}


static GRegex*
adblock_filter_real_lookup (AdblockFilter* self,
                            const gchar* sig)
{
	GRegex* result = NULL;
	GHashTable* _tmp0_;
	gconstpointer _tmp1_;
	GRegex* _tmp2_;
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_val_if_fail (sig != NULL, NULL);
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp0_ = self->rules;
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp1_ = g_hash_table_lookup (_tmp0_, sig);
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp2_ = _g_regex_ref0 ((GRegex*) _tmp1_);
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	result = _tmp2_;
#line 23 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	return result;
#line 121 "filter.c"
}


GRegex*
adblock_filter_lookup (AdblockFilter* self,
                       const gchar* sig)
{
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 22 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	return ADBLOCK_FILTER_GET_CLASS (self)->lookup (self, sig);
#line 133 "filter.c"
}


static guint
adblock_filter_real_size (AdblockFilter* self)
{
	guint result = 0U;
	GHashTable* _tmp0_;
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp0_ = self->rules;
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	result = g_hash_table_size (_tmp0_);
#line 27 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	return result;
#line 148 "filter.c"
}


guint
adblock_filter_size (AdblockFilter* self)
{
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_val_if_fail (self != NULL, 0U);
#line 26 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	return ADBLOCK_FILTER_GET_CLASS (self)->size (self);
#line 159 "filter.c"
}


static gpointer
_g_object_ref0 (gpointer self)
{
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	return self ? g_object_ref (self) : NULL;
#line 168 "filter.c"
}


AdblockFilter*
adblock_filter_construct (GType object_type,
                          AdblockOptions* options)
{
	AdblockFilter * self = NULL;
	AdblockOptions* _tmp0_;
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_val_if_fail (options != NULL, NULL);
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	self = (AdblockFilter*) adblock_feature_construct (object_type);
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp0_ = _g_object_ref0 (options);
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_g_object_unref0 (self->priv->optslist);
#line 31 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	self->priv->optslist = _tmp0_;
#line 32 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	adblock_feature_clear ((AdblockFeature*) self);
#line 30 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	return self;
#line 192 "filter.c"
}


static void
_g_free0_ (gpointer var)
{
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	var = (g_free (var), NULL);
#line 201 "filter.c"
}


static void
_g_regex_unref0_ (gpointer var)
{
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	(var == NULL) ? NULL : (var = (g_regex_unref (var), NULL));
#line 210 "filter.c"
}


static void
adblock_filter_real_clear (AdblockFeature* base)
{
	AdblockFilter * self;
	GHashFunc _tmp0_;
	GEqualFunc _tmp1_;
	GHashTable* _tmp2_;
#line 35 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	self = (AdblockFilter*) base;
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp0_ = g_str_hash;
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp1_ = g_str_equal;
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp2_ = g_hash_table_new_full (_tmp0_, _tmp1_, _g_free0_, _g_regex_unref0_);
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_g_hash_table_unref0 (self->rules);
#line 36 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	self->rules = _tmp2_;
#line 233 "filter.c"
}


gboolean
adblock_filter_check_rule (AdblockFilter* self,
                           GRegex* regex,
                           const gchar* pattern,
                           const gchar* request_uri,
                           const gchar* page_uri,
                           GError** error)
{
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_;
	gchar* opts = NULL;
	AdblockOptions* _tmp3_;
	gchar* _tmp4_;
	gboolean _tmp5_ = FALSE;
	const gchar* _tmp6_;
	const gchar* _tmp12_;
	GError * _inner_error_ = NULL;
#line 39 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 39 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_val_if_fail (regex != NULL, FALSE);
#line 39 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_val_if_fail (pattern != NULL, FALSE);
#line 39 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_val_if_fail (request_uri != NULL, FALSE);
#line 39 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_return_val_if_fail (page_uri != NULL, FALSE);
#line 40 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp1_ = g_regex_match_full (regex, request_uri, (gssize) -1, 0, 0, NULL, &_inner_error_);
#line 40 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp0_ = _tmp1_;
#line 40 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 271 "filter.c"
		gboolean _tmp2_ = FALSE;
#line 40 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
		g_propagate_error (error, _inner_error_);
#line 40 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
		return _tmp2_;
#line 277 "filter.c"
	}
#line 40 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	if (!_tmp0_) {
#line 41 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
		result = FALSE;
#line 41 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
		return result;
#line 285 "filter.c"
	}
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp3_ = self->priv->optslist;
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp4_ = adblock_options_lookup (_tmp3_, pattern);
#line 43 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	opts = _tmp4_;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp6_ = opts;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	if (_tmp6_ != NULL) {
#line 297 "filter.c"
		const gchar* _tmp7_;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
		_tmp7_ = opts;
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
		_tmp5_ = g_regex_match_simple (",third-party", _tmp7_, G_REGEX_CASELESS, G_REGEX_MATCH_NOTEMPTY);
#line 303 "filter.c"
	} else {
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
		_tmp5_ = FALSE;
#line 307 "filter.c"
	}
#line 44 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	if (_tmp5_) {
#line 311 "filter.c"
		gboolean _tmp8_ = FALSE;
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
		if (page_uri != NULL) {
#line 315 "filter.c"
			gboolean _tmp9_ = FALSE;
			gboolean _tmp10_;
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
			_tmp10_ = g_regex_match_full (regex, page_uri, (gssize) -1, 0, 0, NULL, &_inner_error_);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
			_tmp9_ = _tmp10_;
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 324 "filter.c"
				gboolean _tmp11_ = FALSE;
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
				g_propagate_error (error, _inner_error_);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
				_g_free0 (opts);
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
				return _tmp11_;
#line 332 "filter.c"
			}
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
			_tmp8_ = _tmp9_;
#line 336 "filter.c"
		} else {
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
			_tmp8_ = FALSE;
#line 340 "filter.c"
		}
#line 46 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
		if (_tmp8_) {
#line 47 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
			result = FALSE;
#line 47 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
			_g_free0 (opts);
#line 47 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
			return result;
#line 350 "filter.c"
		}
	}
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_tmp12_ = g_regex_get_pattern (regex);
#line 48 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	adblock_debug ("blocked by pattern regexp=%s -- %s", _tmp12_, request_uri, NULL);
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	result = TRUE;
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_g_free0 (opts);
#line 49 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	return result;
#line 363 "filter.c"
}


static void
adblock_filter_class_init (AdblockFilterClass * klass)
{
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	adblock_filter_parent_class = g_type_class_peek_parent (klass);
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	g_type_class_add_private (klass, sizeof (AdblockFilterPrivate));
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	((AdblockFilterClass *) klass)->insert = (void (*) (AdblockFilter *, const gchar*, GRegex*)) adblock_filter_real_insert;
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	((AdblockFilterClass *) klass)->lookup = (GRegex* (*) (AdblockFilter *, const gchar*)) adblock_filter_real_lookup;
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	((AdblockFilterClass *) klass)->size = (guint (*) (AdblockFilter *)) adblock_filter_real_size;
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	((AdblockFeatureClass *) klass)->clear = (void (*) (AdblockFeature *)) adblock_filter_real_clear;
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	G_OBJECT_CLASS (klass)->finalize = adblock_filter_finalize;
#line 384 "filter.c"
}


static void
adblock_filter_instance_init (AdblockFilter * self)
{
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	self->priv = ADBLOCK_FILTER_GET_PRIVATE (self);
#line 393 "filter.c"
}


static void
adblock_filter_finalize (GObject * obj)
{
	AdblockFilter * self;
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ADBLOCK_TYPE_FILTER, AdblockFilter);
#line 15 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_g_object_unref0 (self->priv->optslist);
#line 16 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	_g_hash_table_unref0 (self->rules);
#line 14 "/home/midiba/Documents/glibc/pvd-aware-app/midori/extensions/adblock/filter.vala"
	G_OBJECT_CLASS (adblock_filter_parent_class)->finalize (obj);
#line 409 "filter.c"
}


GType
adblock_filter_get_type (void)
{
	static volatile gsize adblock_filter_type_id__volatile = 0;
	if (g_once_init_enter (&adblock_filter_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AdblockFilterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) adblock_filter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AdblockFilter), 0, (GInstanceInitFunc) adblock_filter_instance_init, NULL };
		GType adblock_filter_type_id;
		adblock_filter_type_id = g_type_register_static (ADBLOCK_TYPE_FEATURE, "AdblockFilter", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&adblock_filter_type_id__volatile, adblock_filter_type_id);
	}
	return adblock_filter_type_id__volatile;
}



